// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Mocks generated by Mockito 5.4.4 from annotations
// in google_maps_driver/test/google_maps_driver_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:google_maps_driver/src/method_channel/messages.g.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'messages_test.g.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeliveryVehicleDto_0 extends _i1.SmartFake
    implements _i2.DeliveryVehicleDto {
  _FakeDeliveryVehicleDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TestCommonDriverApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestCommonDriverApi extends _i1.Mock
    implements _i3.TestCommonDriverApi {
  MockTestCommonDriverApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void initialize(
    _i2.DriverApiTypeDto? type,
    String? providerId,
    String? vehicleId,
    bool? abnormalTerminationReportingEnabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            type,
            providerId,
            vehicleId,
            abnormalTerminationReportingEnabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isInitialized(_i2.DriverApiTypeDto? type) => (super.noSuchMethod(
        Invocation.method(
          #isInitialized,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getProviderId(_i2.DriverApiTypeDto? type) => (super.noSuchMethod(
        Invocation.method(
          #getProviderId,
          [type],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getProviderId,
            [type],
          ),
        ),
      ) as String);

  @override
  String getVehicleId(_i2.DriverApiTypeDto? type) => (super.noSuchMethod(
        Invocation.method(
          #getVehicleId,
          [type],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getVehicleId,
            [type],
          ),
        ),
      ) as String);

  @override
  bool isLocationTrackingEnabled(_i2.DriverApiTypeDto? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLocationTrackingEnabled,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setLocationTrackingEnabled(
    _i2.DriverApiTypeDto? type,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLocationTrackingEnabled,
          [
            type,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getLocationReportingIntervalMillis(_i2.DriverApiTypeDto? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationReportingIntervalMillis,
          [type],
        ),
        returnValue: 0,
      ) as int);

  @override
  void setLocationReportingIntervalMillis(
    _i2.DriverApiTypeDto? type,
    int? milliseconds,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLocationReportingIntervalMillis,
          [
            type,
            milliseconds,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose(_i2.DriverApiTypeDto? type) => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getDriverSdkVersion(_i2.DriverApiTypeDto? type) => (super.noSuchMethod(
        Invocation.method(
          #getDriverSdkVersion,
          [type],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getDriverSdkVersion,
            [type],
          ),
        ),
      ) as String);

  @override
  void setSupplementalLocation(
    _i2.DriverApiTypeDto? type,
    _i2.LocationDto? location,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSupplementalLocation,
          [
            type,
            location,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TestDeliveryDriverApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestDeliveryDriverApi extends _i1.Mock
    implements _i3.TestDeliveryDriverApi {
  MockTestDeliveryDriverApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.VehicleStopDto?>> arrivedAtStop() => (super.noSuchMethod(
        Invocation.method(
          #arrivedAtStop,
          [],
        ),
        returnValue: _i5.Future<List<_i2.VehicleStopDto?>>.value(
            <_i2.VehicleStopDto?>[]),
      ) as _i5.Future<List<_i2.VehicleStopDto?>>);

  @override
  _i5.Future<List<_i2.VehicleStopDto?>> completedStop() => (super.noSuchMethod(
        Invocation.method(
          #completedStop,
          [],
        ),
        returnValue: _i5.Future<List<_i2.VehicleStopDto?>>.value(
            <_i2.VehicleStopDto?>[]),
      ) as _i5.Future<List<_i2.VehicleStopDto?>>);

  @override
  _i5.Future<List<_i2.VehicleStopDto?>> enrouteToNextStop() =>
      (super.noSuchMethod(
        Invocation.method(
          #enrouteToNextStop,
          [],
        ),
        returnValue: _i5.Future<List<_i2.VehicleStopDto?>>.value(
            <_i2.VehicleStopDto?>[]),
      ) as _i5.Future<List<_i2.VehicleStopDto?>>);

  @override
  _i5.Future<List<_i2.VehicleStopDto?>> getRemainingVehicleStops() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemainingVehicleStops,
          [],
        ),
        returnValue: _i5.Future<List<_i2.VehicleStopDto?>>.value(
            <_i2.VehicleStopDto?>[]),
      ) as _i5.Future<List<_i2.VehicleStopDto?>>);

  @override
  _i5.Future<List<_i2.VehicleStopDto?>> setVehicleStops(
          List<_i2.VehicleStopDto?>? stops) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVehicleStops,
          [stops],
        ),
        returnValue: _i5.Future<List<_i2.VehicleStopDto?>>.value(
            <_i2.VehicleStopDto?>[]),
      ) as _i5.Future<List<_i2.VehicleStopDto?>>);

  @override
  _i5.Future<_i2.DeliveryVehicleDto> getDeliveryVehicle() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryVehicle,
          [],
        ),
        returnValue:
            _i5.Future<_i2.DeliveryVehicleDto>.value(_FakeDeliveryVehicleDto_0(
          this,
          Invocation.method(
            #getDeliveryVehicle,
            [],
          ),
        )),
      ) as _i5.Future<_i2.DeliveryVehicleDto>);
}

/// A class which mocks [TestRidesharingDriverApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestRidesharingDriverApi extends _i1.Mock
    implements _i3.TestRidesharingDriverApi {
  MockTestRidesharingDriverApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setVehicleState(_i2.VehicleStateDto? state) => super.noSuchMethod(
        Invocation.method(
          #setVehicleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
}
