// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:google_driver_flutter/src/method_channel/messages.g.dart';

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is DriverApiTypeDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is VehicleStopStateDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is VehicleStateDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is DriverStatusLevelDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is DriverStatusCodeDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is TaskInfoDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is VehicleStopDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is LatLngDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is NavigationWaypointDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is LocationDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is DeliveryVehicleDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is VehicleUpdateDto) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DriverApiTypeDto.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VehicleStopStateDto.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VehicleStateDto.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DriverStatusLevelDto.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DriverStatusCodeDto.values[value];
      case 134:
        return TaskInfoDto.decode(readValue(buffer)!);
      case 135:
        return VehicleStopDto.decode(readValue(buffer)!);
      case 136:
        return LatLngDto.decode(readValue(buffer)!);
      case 137:
        return NavigationWaypointDto.decode(readValue(buffer)!);
      case 138:
        return LocationDto.decode(readValue(buffer)!);
      case 139:
        return DeliveryVehicleDto.decode(readValue(buffer)!);
      case 140:
        return VehicleUpdateDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class TestCommonDriverApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding =>
      TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void initialize(
    DriverApiTypeDto type,
    String providerId,
    String vehicleId,
    bool abnormalTerminationReportingEnabled,
  );

  bool isInitialized(DriverApiTypeDto type);

  String getProviderId(DriverApiTypeDto type);

  String getVehicleId(DriverApiTypeDto type);

  bool isLocationTrackingEnabled(DriverApiTypeDto type);

  void setLocationTrackingEnabled(DriverApiTypeDto type, bool enabled);

  int getLocationReportingIntervalMillis(DriverApiTypeDto type);

  void setLocationReportingIntervalMillis(
    DriverApiTypeDto type,
    int milliseconds,
  );

  void dispose(DriverApiTypeDto type);

  String getDriverSdkVersion(DriverApiTypeDto type);

  void setSupplementalLocation(DriverApiTypeDto type, LocationDto location);

  static void setUp(
    TestCommonDriverApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<
          Object?
        >(pigeonVar_channel, (Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
          assert(
            arg_type != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize was null, expected non-null DriverApiTypeDto.',
          );
          final String? arg_providerId = (args[1] as String?);
          assert(
            arg_providerId != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize was null, expected non-null String.',
          );
          final String? arg_vehicleId = (args[2] as String?);
          assert(
            arg_vehicleId != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize was null, expected non-null String.',
          );
          final bool? arg_abnormalTerminationReportingEnabled =
              (args[3] as bool?);
          assert(
            arg_abnormalTerminationReportingEnabled != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize was null, expected non-null bool.',
          );
          try {
            api.initialize(
              arg_type!,
              arg_providerId!,
              arg_vehicleId!,
              arg_abnormalTerminationReportingEnabled!,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
              assert(
                arg_type != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized was null, expected non-null DriverApiTypeDto.',
              );
              try {
                final bool output = api.isInitialized(arg_type!);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
              assert(
                arg_type != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId was null, expected non-null DriverApiTypeDto.',
              );
              try {
                final String output = api.getProviderId(arg_type!);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
              assert(
                arg_type != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId was null, expected non-null DriverApiTypeDto.',
              );
              try {
                final String output = api.getVehicleId(arg_type!);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
              assert(
                arg_type != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled was null, expected non-null DriverApiTypeDto.',
              );
              try {
                final bool output = api.isLocationTrackingEnabled(arg_type!);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<
          Object?
        >(pigeonVar_channel, (Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
          assert(
            arg_type != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled was null, expected non-null DriverApiTypeDto.',
          );
          final bool? arg_enabled = (args[1] as bool?);
          assert(
            arg_enabled != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled was null, expected non-null bool.',
          );
          try {
            api.setLocationTrackingEnabled(arg_type!, arg_enabled!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
              assert(
                arg_type != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis was null, expected non-null DriverApiTypeDto.',
              );
              try {
                final int output = api.getLocationReportingIntervalMillis(
                  arg_type!,
                );
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<
          Object?
        >(pigeonVar_channel, (Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
          assert(
            arg_type != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis was null, expected non-null DriverApiTypeDto.',
          );
          final int? arg_milliseconds = (args[1] as int?);
          assert(
            arg_milliseconds != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis was null, expected non-null int.',
          );
          try {
            api.setLocationReportingIntervalMillis(
              arg_type!,
              arg_milliseconds!,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
              assert(
                arg_type != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose was null, expected non-null DriverApiTypeDto.',
              );
              try {
                api.dispose(arg_type!);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
              assert(
                arg_type != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion was null, expected non-null DriverApiTypeDto.',
              );
              try {
                final String output = api.getDriverSdkVersion(arg_type!);
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<
          Object?
        >(pigeonVar_channel, (Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final DriverApiTypeDto? arg_type = (args[0] as DriverApiTypeDto?);
          assert(
            arg_type != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation was null, expected non-null DriverApiTypeDto.',
          );
          final LocationDto? arg_location = (args[1] as LocationDto?);
          assert(
            arg_location != null,
            'Argument for dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation was null, expected non-null LocationDto.',
          );
          try {
            api.setSupplementalLocation(arg_type!, arg_location!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

abstract class TestDeliveryDriverApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding =>
      TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<List<VehicleStopDto>> arrivedAtStop();

  Future<List<VehicleStopDto>> completedStop();

  Future<List<VehicleStopDto>> enrouteToNextStop();

  Future<List<VehicleStopDto>> getRemainingVehicleStops();

  Future<List<VehicleStopDto>> setVehicleStops(List<VehicleStopDto> stops);

  Future<DeliveryVehicleDto> getDeliveryVehicle();

  static void setUp(
    TestDeliveryDriverApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.arrivedAtStop$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              try {
                final List<VehicleStopDto> output = await api.arrivedAtStop();
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.completedStop$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              try {
                final List<VehicleStopDto> output = await api.completedStop();
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.enrouteToNextStop$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              try {
                final List<VehicleStopDto> output = await api
                    .enrouteToNextStop();
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getRemainingVehicleStops$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              try {
                final List<VehicleStopDto> output = await api
                    .getRemainingVehicleStops();
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final List<VehicleStopDto>? arg_stops =
                  (args[0] as List<Object?>?)?.cast<VehicleStopDto>();
              assert(
                arg_stops != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops was null, expected non-null List<VehicleStopDto>.',
              );
              try {
                final List<VehicleStopDto> output = await api.setVehicleStops(
                  arg_stops!,
                );
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getDeliveryVehicle$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              try {
                final DeliveryVehicleDto output = await api
                    .getDeliveryVehicle();
                return <Object?>[output];
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
  }
}

abstract class TestRidesharingDriverApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding =>
      TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void setVehicleState(VehicleStateDto state);

  static void setUp(
    TestRidesharingDriverApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger
            .setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (
              Object? message,
            ) async {
              assert(
                message != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState was null.',
              );
              final List<Object?> args = (message as List<Object?>?)!;
              final VehicleStateDto? arg_state = (args[0] as VehicleStateDto?);
              assert(
                arg_state != null,
                'Argument for dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState was null, expected non-null VehicleStateDto.',
              );
              try {
                api.setVehicleState(arg_state!);
                return wrapResponse(empty: true);
              } on PlatformException catch (e) {
                return wrapResponse(error: e);
              } catch (e) {
                return wrapResponse(
                  error: PlatformException(
                    code: 'error',
                    message: e.toString(),
                  ),
                );
              }
            });
      }
    }
  }
}
