// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Autogenerated from Pigeon (v15.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  FlutterError(
    code: "channel-error",
    message: "Unable to establish connection on channel: '\(channelName)'.",
    details: ""
  )
}

private func isNullish(_ value: Any?) -> Bool {
  value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Indicates the API type for a driver.
enum DriverApiTypeDto: Int {
  /// Indicates the API is for a delivery driver.
  case delivery = 0
  /// Indicates the API is for a ridesharing driver.
  case ridesharing = 1
}

enum VehicleStopStateDto: Int {
  case stateUnspecified = 0
  case newStop = 1
  case enroute = 2
  case arrived = 3
}

enum VehicleStateDto: Int {
  /// Indicates the vehicle is not accepting new trips.
  case offline = 0
  /// Indicates the vehicle is accepting new trips.
  case online = 1
}

enum DriverStatusLevelDto: Int {
  case debug = 0
  case info = 1
  case warning = 2
  case error = 3
}

enum DriverStatusCodeDto: Int {
  case defaultStatus = 0
  case unknownError = 1
  case vehicleNotFound = 2
  case backendConnectivityError = 3
  case permissionDenied = 4
  case serviceError = 5
  case fileAccessError = 6
  case traveledRouteError = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct TaskInfoDto {
  var taskId: String
  var durationSeconds: Int64

  static func fromList(_ list: [Any?]) -> TaskInfoDto? {
    let taskId = list[0] as! String
    let durationSeconds = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)

    return TaskInfoDto(
      taskId: taskId,
      durationSeconds: durationSeconds
    )
  }

  func toList() -> [Any?] {
    [
      taskId,
      durationSeconds,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VehicleStopDto {
  var vehicleStopState: VehicleStopStateDto
  var waypoint: NavigationWaypointDto?
  var taskInfoList: [TaskInfoDto?]

  static func fromList(_ list: [Any?]) -> VehicleStopDto? {
    let vehicleStopState = VehicleStopStateDto(rawValue: list[0] as! Int)!
    var waypoint: NavigationWaypointDto?
    if let waypointList: [Any?] = nilOrValue(list[1]) {
      waypoint = NavigationWaypointDto.fromList(waypointList)
    }
    let taskInfoList = list[2] as! [TaskInfoDto?]

    return VehicleStopDto(
      vehicleStopState: vehicleStopState,
      waypoint: waypoint,
      taskInfoList: taskInfoList
    )
  }

  func toList() -> [Any?] {
    [
      vehicleStopState.rawValue,
      waypoint?.toList(),
      taskInfoList,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LatLngDto {
  var latitude: Double
  var longitude: Double

  static func fromList(_ list: [Any?]) -> LatLngDto? {
    let latitude = list[0] as! Double
    let longitude = list[1] as! Double

    return LatLngDto(
      latitude: latitude,
      longitude: longitude
    )
  }

  func toList() -> [Any?] {
    [
      latitude,
      longitude,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NavigationWaypointDto {
  var title: String
  var target: LatLngDto?
  var placeID: String?
  var preferSameSideOfRoad: Bool?
  var preferredSegmentHeading: Int64?

  static func fromList(_ list: [Any?]) -> NavigationWaypointDto? {
    let title = list[0] as! String
    var target: LatLngDto?
    if let targetList: [Any?] = nilOrValue(list[1]) {
      target = LatLngDto.fromList(targetList)
    }
    let placeID: String? = nilOrValue(list[2])
    let preferSameSideOfRoad: Bool? = nilOrValue(list[3])
    let preferredSegmentHeading: Int64? =
      isNullish(list[4]) ? nil : (list[4] is Int64? ? list[4] as! Int64? : Int64(list[4] as! Int32))

    return NavigationWaypointDto(
      title: title,
      target: target,
      placeID: placeID,
      preferSameSideOfRoad: preferSameSideOfRoad,
      preferredSegmentHeading: preferredSegmentHeading
    )
  }

  func toList() -> [Any?] {
    [
      title,
      target?.toList(),
      placeID,
      preferSameSideOfRoad,
      preferredSegmentHeading,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LocationDto {
  var accuracy: Double?
  var altitude: Double?
  var elapsedRealtimeNanos: Int64?
  var bearing: Double?
  var isMock: Bool?
  var latitude: Double?
  var longitude: Double?
  var provider: String?
  var speed: Double?
  var time: Int64?

  static func fromList(_ list: [Any?]) -> LocationDto? {
    let accuracy: Double? = nilOrValue(list[0])
    let altitude: Double? = nilOrValue(list[1])
    let elapsedRealtimeNanos: Int64? =
      isNullish(list[2]) ? nil : (list[2] is Int64? ? list[2] as! Int64? : Int64(list[2] as! Int32))
    let bearing: Double? = nilOrValue(list[3])
    let isMock: Bool? = nilOrValue(list[4])
    let latitude: Double? = nilOrValue(list[5])
    let longitude: Double? = nilOrValue(list[6])
    let provider: String? = nilOrValue(list[7])
    let speed: Double? = nilOrValue(list[8])
    let time: Int64? =
      isNullish(list[9]) ? nil : (list[9] is Int64? ? list[9] as! Int64? : Int64(list[9] as! Int32))

    return LocationDto(
      accuracy: accuracy,
      altitude: altitude,
      elapsedRealtimeNanos: elapsedRealtimeNanos,
      bearing: bearing,
      isMock: isMock,
      latitude: latitude,
      longitude: longitude,
      provider: provider,
      speed: speed,
      time: time
    )
  }

  func toList() -> [Any?] {
    [
      accuracy,
      altitude,
      elapsedRealtimeNanos,
      bearing,
      isMock,
      latitude,
      longitude,
      provider,
      speed,
      time,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeliveryVehicleDto {
  var providerId: String
  var id: String
  var name: String
  var stops: [VehicleStopDto?]

  static func fromList(_ list: [Any?]) -> DeliveryVehicleDto? {
    let providerId = list[0] as! String
    let id = list[1] as! String
    let name = list[2] as! String
    let stops = list[3] as! [VehicleStopDto?]

    return DeliveryVehicleDto(
      providerId: providerId,
      id: id,
      name: name,
      stops: stops
    )
  }

  func toList() -> [Any?] {
    [
      providerId,
      id,
      name,
      stops,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VehicleUpdateDto {
  var vehicleState: VehicleStateDto?
  var location: LatLngDto?
  var destinationWaypoint: NavigationWaypointDto?
  var route: [LatLngDto?]?
  var remainingTimeInSeconds: Double?
  var remainingDistanceInMeters: Double?

  static func fromList(_ list: [Any?]) -> VehicleUpdateDto? {
    var vehicleState: VehicleStateDto?
    let vehicleStateEnumVal: Int? = nilOrValue(list[0])
    if let vehicleStateRawValue = vehicleStateEnumVal {
      vehicleState = VehicleStateDto(rawValue: vehicleStateRawValue)!
    }
    var location: LatLngDto?
    if let locationList: [Any?] = nilOrValue(list[1]) {
      location = LatLngDto.fromList(locationList)
    }
    var destinationWaypoint: NavigationWaypointDto?
    if let destinationWaypointList: [Any?] = nilOrValue(list[2]) {
      destinationWaypoint = NavigationWaypointDto.fromList(destinationWaypointList)
    }
    let route: [LatLngDto?]? = nilOrValue(list[3])
    let remainingTimeInSeconds: Double? = nilOrValue(list[4])
    let remainingDistanceInMeters: Double? = nilOrValue(list[5])

    return VehicleUpdateDto(
      vehicleState: vehicleState,
      location: location,
      destinationWaypoint: destinationWaypoint,
      route: route,
      remainingTimeInSeconds: remainingTimeInSeconds,
      remainingDistanceInMeters: remainingDistanceInMeters
    )
  }

  func toList() -> [Any?] {
    [
      vehicleState?.rawValue,
      location?.toList(),
      destinationWaypoint?.toList(),
      route,
      remainingTimeInSeconds,
      remainingDistanceInMeters,
    ]
  }
}

private class CommonDriverApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return LocationDto.fromList(readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CommonDriverApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LocationDto {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CommonDriverApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    CommonDriverApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    CommonDriverApiCodecWriter(data: data)
  }
}

class CommonDriverApiCodec: FlutterStandardMessageCodec {
  static let shared = CommonDriverApiCodec(readerWriter: CommonDriverApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CommonDriverApi {
  func initialize(
    type: DriverApiTypeDto, providerId: String, vehicleId: String,
    abnormalTerminationReportingEnabled: Bool) throws
  func isInitialized(type: DriverApiTypeDto) throws -> Bool
  func getProviderId(type: DriverApiTypeDto) throws -> String
  func getVehicleId(type: DriverApiTypeDto) throws -> String
  func isLocationTrackingEnabled(type: DriverApiTypeDto) throws -> Bool
  func setLocationTrackingEnabled(type: DriverApiTypeDto, enabled: Bool) throws
  func getLocationReportingIntervalMillis(type: DriverApiTypeDto) throws -> Int64
  func setLocationReportingIntervalMillis(type: DriverApiTypeDto, milliseconds: Int64) throws
  func dispose(type: DriverApiTypeDto) throws
  func getDriverSdkVersion(type: DriverApiTypeDto) throws -> String
  func setSupplementalLocation(type: DriverApiTypeDto, location: LocationDto) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
enum CommonDriverApiSetup {
  /// The codec used by CommonDriverApi.
  static var codec: FlutterStandardMessageCodec { CommonDriverApiCodec.shared }
  /// Sets up an instance of `CommonDriverApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CommonDriverApi?) {
    let initializeChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        let providerIdArg = args[1] as! String
        let vehicleIdArg = args[2] as! String
        let abnormalTerminationReportingEnabledArg = args[3] as! Bool
        do {
          try api.initialize(
            type: typeArg,
            providerId: providerIdArg,
            vehicleId: vehicleIdArg,
            abnormalTerminationReportingEnabled: abnormalTerminationReportingEnabledArg
          )
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let isInitializedChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      isInitializedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        do {
          let result = try api.isInitialized(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isInitializedChannel.setMessageHandler(nil)
    }
    let getProviderIdChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      getProviderIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        do {
          let result = try api.getProviderId(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getProviderIdChannel.setMessageHandler(nil)
    }
    let getVehicleIdChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      getVehicleIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        do {
          let result = try api.getVehicleId(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVehicleIdChannel.setMessageHandler(nil)
    }
    let isLocationTrackingEnabledChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      isLocationTrackingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        do {
          let result = try api.isLocationTrackingEnabled(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isLocationTrackingEnabledChannel.setMessageHandler(nil)
    }
    let setLocationTrackingEnabledChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      setLocationTrackingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        let enabledArg = args[1] as! Bool
        do {
          try api.setLocationTrackingEnabled(type: typeArg, enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLocationTrackingEnabledChannel.setMessageHandler(nil)
    }
    let getLocationReportingIntervalMillisChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      getLocationReportingIntervalMillisChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        do {
          let result = try api.getLocationReportingIntervalMillis(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLocationReportingIntervalMillisChannel.setMessageHandler(nil)
    }
    let setLocationReportingIntervalMillisChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      setLocationReportingIntervalMillisChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        let millisecondsArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        do {
          try api.setLocationReportingIntervalMillis(type: typeArg, milliseconds: millisecondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLocationReportingIntervalMillisChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        do {
          try api.dispose(type: typeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let getDriverSdkVersionChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      getDriverSdkVersionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        do {
          let result = try api.getDriverSdkVersion(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDriverSdkVersionChannel.setMessageHandler(nil)
    }
    let setSupplementalLocationChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      setSupplementalLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = DriverApiTypeDto(rawValue: args[0] as! Int)!
        let locationArg = args[1] as! LocationDto
        do {
          try api.setSupplementalLocation(type: typeArg, location: locationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSupplementalLocationChannel.setMessageHandler(nil)
    }
  }
}

private class DeliveryDriverApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return DeliveryVehicleDto.fromList(readValue() as! [Any?])
    case 129:
      return LatLngDto.fromList(readValue() as! [Any?])
    case 130:
      return NavigationWaypointDto.fromList(readValue() as! [Any?])
    case 131:
      return TaskInfoDto.fromList(readValue() as! [Any?])
    case 132:
      return VehicleStopDto.fromList(readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DeliveryDriverApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DeliveryVehicleDto {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? LatLngDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NavigationWaypointDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? TaskInfoDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? VehicleStopDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DeliveryDriverApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    DeliveryDriverApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    DeliveryDriverApiCodecWriter(data: data)
  }
}

class DeliveryDriverApiCodec: FlutterStandardMessageCodec {
  static let shared = DeliveryDriverApiCodec(readerWriter: DeliveryDriverApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeliveryDriverApi {
  func arrivedAtStop(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func completedStop(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func enrouteToNextStop(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func getRemainingVehicleStops(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func setVehicleStops(
    stops: [VehicleStopDto],
    completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func getDeliveryVehicle(completion: @escaping (Result<DeliveryVehicleDto, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
enum DeliveryDriverApiSetup {
  /// The codec used by DeliveryDriverApi.
  static var codec: FlutterStandardMessageCodec { DeliveryDriverApiCodec.shared }
  /// Sets up an instance of `DeliveryDriverApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeliveryDriverApi?) {
    let arrivedAtStopChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.arrivedAtStop",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      arrivedAtStopChannel.setMessageHandler { _, reply in
        api.arrivedAtStop { result in
          switch result {
          case let .success(res):
            reply(wrapResult(res))
          case let .failure(error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      arrivedAtStopChannel.setMessageHandler(nil)
    }
    let completedStopChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.completedStop",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      completedStopChannel.setMessageHandler { _, reply in
        api.completedStop { result in
          switch result {
          case let .success(res):
            reply(wrapResult(res))
          case let .failure(error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      completedStopChannel.setMessageHandler(nil)
    }
    let enrouteToNextStopChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.enrouteToNextStop",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      enrouteToNextStopChannel.setMessageHandler { _, reply in
        api.enrouteToNextStop { result in
          switch result {
          case let .success(res):
            reply(wrapResult(res))
          case let .failure(error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enrouteToNextStopChannel.setMessageHandler(nil)
    }
    let getRemainingVehicleStopsChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getRemainingVehicleStops",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      getRemainingVehicleStopsChannel.setMessageHandler { _, reply in
        api.getRemainingVehicleStops { result in
          switch result {
          case let .success(res):
            reply(wrapResult(res))
          case let .failure(error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getRemainingVehicleStopsChannel.setMessageHandler(nil)
    }
    let setVehicleStopsChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      setVehicleStopsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stopsArg = args[0] as! [VehicleStopDto]
        api.setVehicleStops(stops: stopsArg) { result in
          switch result {
          case let .success(res):
            reply(wrapResult(res))
          case let .failure(error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setVehicleStopsChannel.setMessageHandler(nil)
    }
    let getDeliveryVehicleChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getDeliveryVehicle",
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    if let api {
      getDeliveryVehicleChannel.setMessageHandler { _, reply in
        api.getDeliveryVehicle { result in
          switch result {
          case let .success(res):
            reply(wrapResult(res))
          case let .failure(error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeliveryVehicleChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RidesharingDriverApi {
  func setVehicleState(state: VehicleStateDto) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
enum RidesharingDriverApiSetup {
  /// The codec used by RidesharingDriverApi.
  /// Sets up an instance of `RidesharingDriverApi` to handle messages through the
  /// `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RidesharingDriverApi?) {
    let setVehicleStateChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState",
      binaryMessenger: binaryMessenger
    )
    if let api {
      setVehicleStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = VehicleStateDto(rawValue: args[0] as! Int)!
        do {
          try api.setVehicleState(state: stateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVehicleStateChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AuthTokenEventApiProtocol {
  func getToken(
    taskId taskIdArg: String?, vehicleId vehicleIdArg: String?,
    completion: @escaping (Result<String, FlutterError>) -> Void)
}

class AuthTokenEventApi: AuthTokenEventApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger) {
    self.binaryMessenger = binaryMessenger
  }

  func getToken(
    taskId taskIdArg: String?, vehicleId vehicleIdArg: String?,
    completion: @escaping (Result<String, FlutterError>) -> Void
  ) {
    let channelName = "dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger)
    channel.sendMessage([taskIdArg, vehicleIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            FlutterError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.",
              details: ""
            )))
      } else {
        let result = listResponse[0] as! String
        completion(.success(result))
      }
    }
  }
}

private class VehicleReporterListenerApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return LatLngDto.fromList(readValue() as! [Any?])
    case 129:
      return LatLngDto.fromList(readValue() as! [Any?])
    case 130:
      return NavigationWaypointDto.fromList(readValue() as! [Any?])
    case 131:
      return VehicleUpdateDto.fromList(readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VehicleReporterListenerApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LatLngDto {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? LatLngDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NavigationWaypointDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VehicleUpdateDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VehicleReporterListenerApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    VehicleReporterListenerApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    VehicleReporterListenerApiCodecWriter(data: data)
  }
}

class VehicleReporterListenerApiCodec: FlutterStandardMessageCodec {
  static let shared =
    VehicleReporterListenerApiCodec(readerWriter: VehicleReporterListenerApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VehicleReporterListenerApiProtocol {
  func onDidSucceed(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto,
    completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onDidFail(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto, errorCode errorCodeArg: String,
    errorMessage errorMessageArg: String,
    completion: @escaping (Result<Void, FlutterError>) -> Void)
}

class VehicleReporterListenerApi: VehicleReporterListenerApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger) {
    self.binaryMessenger = binaryMessenger
  }

  var codec: FlutterStandardMessageCodec {
    VehicleReporterListenerApiCodec.shared
  }

  func onDidSucceed(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto,
    completion: @escaping (Result<Void, FlutterError>) -> Void
  ) {
    let channelName =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed"
    let channel = FlutterBasicMessageChannel(
      name: channelName,
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    channel.sendMessage([vehicleUpdateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }

  func onDidFail(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto, errorCode errorCodeArg: String,
    errorMessage errorMessageArg: String,
    completion: @escaping (Result<Void, FlutterError>) -> Void
  ) {
    let channelName =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail"
    let channel = FlutterBasicMessageChannel(
      name: channelName,
      binaryMessenger: binaryMessenger,
      codec: codec
    )
    channel.sendMessage([vehicleUpdateArg, errorCodeArg, errorMessageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DriverStatusListenerApiProtocol {
  func onStatusUpdate(
    level levelArg: DriverStatusLevelDto, code codeArg: DriverStatusCodeDto,
    message messageArg: String, errorCode errorCodeArg: String?,
    errorMessage errorMessageArg: String?,
    completion: @escaping (Result<Void, FlutterError>) -> Void)
}

class DriverStatusListenerApi: DriverStatusListenerApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger) {
    self.binaryMessenger = binaryMessenger
  }

  func onStatusUpdate(
    level levelArg: DriverStatusLevelDto, code codeArg: DriverStatusCodeDto,
    message messageArg: String, errorCode errorCodeArg: String?,
    errorMessage errorMessageArg: String?,
    completion: @escaping (Result<Void, FlutterError>) -> Void
  ) {
    let channelName =
      "dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger)
    channel.sendMessage(
      [
        levelArg.rawValue,
        codeArg.rawValue,
        messageArg,
        errorCodeArg,
        errorMessageArg,
      ] as [Any?]
    ) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
