// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(
    code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.",
    details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsmessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsmessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsmessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashmessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
    for item in valueList { deepHashmessages(value: item, hasher: &hasher) }
    return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashmessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

/// Indicates the API type for a driver.
enum DriverApiTypeDto: Int {
  /// Indicates the API is for a delivery driver.
  case delivery = 0
  /// Indicates the API is for a ridesharing driver.
  case ridesharing = 1
}

enum VehicleStopStateDto: Int {
  case stateUnspecified = 0
  case newStop = 1
  case enroute = 2
  case arrived = 3
}

enum VehicleStateDto: Int {
  /// Indicates the vehicle is not accepting new trips.
  case offline = 0
  /// Indicates the vehicle is accepting new trips.
  case online = 1
}

enum DriverStatusLevelDto: Int {
  case debug = 0
  case info = 1
  case warning = 2
  case error = 3
}

enum DriverStatusCodeDto: Int {
  case defaultStatus = 0
  case unknownError = 1
  case vehicleNotFound = 2
  case backendConnectivityError = 3
  case permissionDenied = 4
  case serviceError = 5
  case fileAccessError = 6
  case traveledRouteError = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct TaskInfoDto: Hashable {
  var taskId: String
  var durationSeconds: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TaskInfoDto? {
    let taskId = pigeonVar_list[0] as! String
    let durationSeconds = pigeonVar_list[1] as! Int64

    return TaskInfoDto(
      taskId: taskId,
      durationSeconds: durationSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      taskId,
      durationSeconds,
    ]
  }
  static func == (lhs: TaskInfoDto, rhs: TaskInfoDto) -> Bool {
    return deepEqualsmessages(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashmessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VehicleStopDto: Hashable {
  var vehicleStopState: VehicleStopStateDto
  var waypoint: NavigationWaypointDto? = nil
  var taskInfoList: [TaskInfoDto?]

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VehicleStopDto? {
    let vehicleStopState = pigeonVar_list[0] as! VehicleStopStateDto
    let waypoint: NavigationWaypointDto? = nilOrValue(pigeonVar_list[1])
    let taskInfoList = pigeonVar_list[2] as! [TaskInfoDto?]

    return VehicleStopDto(
      vehicleStopState: vehicleStopState,
      waypoint: waypoint,
      taskInfoList: taskInfoList
    )
  }
  func toList() -> [Any?] {
    return [
      vehicleStopState,
      waypoint,
      taskInfoList,
    ]
  }
  static func == (lhs: VehicleStopDto, rhs: VehicleStopDto) -> Bool {
    return deepEqualsmessages(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashmessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LatLngDto: Hashable {
  var latitude: Double
  var longitude: Double

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LatLngDto? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return LatLngDto(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: LatLngDto, rhs: LatLngDto) -> Bool {
    return deepEqualsmessages(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashmessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NavigationWaypointDto: Hashable {
  var title: String
  var target: LatLngDto? = nil
  var placeID: String? = nil
  var preferSameSideOfRoad: Bool? = nil
  var preferredSegmentHeading: Int64? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NavigationWaypointDto? {
    let title = pigeonVar_list[0] as! String
    let target: LatLngDto? = nilOrValue(pigeonVar_list[1])
    let placeID: String? = nilOrValue(pigeonVar_list[2])
    let preferSameSideOfRoad: Bool? = nilOrValue(pigeonVar_list[3])
    let preferredSegmentHeading: Int64? = nilOrValue(pigeonVar_list[4])

    return NavigationWaypointDto(
      title: title,
      target: target,
      placeID: placeID,
      preferSameSideOfRoad: preferSameSideOfRoad,
      preferredSegmentHeading: preferredSegmentHeading
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      target,
      placeID,
      preferSameSideOfRoad,
      preferredSegmentHeading,
    ]
  }
  static func == (lhs: NavigationWaypointDto, rhs: NavigationWaypointDto) -> Bool {
    return deepEqualsmessages(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashmessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LocationDto: Hashable {
  var accuracy: Double? = nil
  var altitude: Double? = nil
  var elapsedRealtimeNanos: Int64? = nil
  var bearing: Double? = nil
  var isMock: Bool? = nil
  var latitude: Double? = nil
  var longitude: Double? = nil
  var provider: String? = nil
  var speed: Double? = nil
  var time: Int64? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationDto? {
    let accuracy: Double? = nilOrValue(pigeonVar_list[0])
    let altitude: Double? = nilOrValue(pigeonVar_list[1])
    let elapsedRealtimeNanos: Int64? = nilOrValue(pigeonVar_list[2])
    let bearing: Double? = nilOrValue(pigeonVar_list[3])
    let isMock: Bool? = nilOrValue(pigeonVar_list[4])
    let latitude: Double? = nilOrValue(pigeonVar_list[5])
    let longitude: Double? = nilOrValue(pigeonVar_list[6])
    let provider: String? = nilOrValue(pigeonVar_list[7])
    let speed: Double? = nilOrValue(pigeonVar_list[8])
    let time: Int64? = nilOrValue(pigeonVar_list[9])

    return LocationDto(
      accuracy: accuracy,
      altitude: altitude,
      elapsedRealtimeNanos: elapsedRealtimeNanos,
      bearing: bearing,
      isMock: isMock,
      latitude: latitude,
      longitude: longitude,
      provider: provider,
      speed: speed,
      time: time
    )
  }
  func toList() -> [Any?] {
    return [
      accuracy,
      altitude,
      elapsedRealtimeNanos,
      bearing,
      isMock,
      latitude,
      longitude,
      provider,
      speed,
      time,
    ]
  }
  static func == (lhs: LocationDto, rhs: LocationDto) -> Bool {
    return deepEqualsmessages(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashmessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeliveryVehicleDto: Hashable {
  var providerId: String
  var id: String
  var name: String
  var stops: [VehicleStopDto?]

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeliveryVehicleDto? {
    let providerId = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String
    let name = pigeonVar_list[2] as! String
    let stops = pigeonVar_list[3] as! [VehicleStopDto?]

    return DeliveryVehicleDto(
      providerId: providerId,
      id: id,
      name: name,
      stops: stops
    )
  }
  func toList() -> [Any?] {
    return [
      providerId,
      id,
      name,
      stops,
    ]
  }
  static func == (lhs: DeliveryVehicleDto, rhs: DeliveryVehicleDto) -> Bool {
    return deepEqualsmessages(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashmessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VehicleUpdateDto: Hashable {
  var vehicleState: VehicleStateDto? = nil
  var location: LatLngDto? = nil
  var destinationWaypoint: NavigationWaypointDto? = nil
  var route: [LatLngDto?]? = nil
  var remainingTimeInSeconds: Double? = nil
  var remainingDistanceInMeters: Double? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VehicleUpdateDto? {
    let vehicleState: VehicleStateDto? = nilOrValue(pigeonVar_list[0])
    let location: LatLngDto? = nilOrValue(pigeonVar_list[1])
    let destinationWaypoint: NavigationWaypointDto? = nilOrValue(pigeonVar_list[2])
    let route: [LatLngDto?]? = nilOrValue(pigeonVar_list[3])
    let remainingTimeInSeconds: Double? = nilOrValue(pigeonVar_list[4])
    let remainingDistanceInMeters: Double? = nilOrValue(pigeonVar_list[5])

    return VehicleUpdateDto(
      vehicleState: vehicleState,
      location: location,
      destinationWaypoint: destinationWaypoint,
      route: route,
      remainingTimeInSeconds: remainingTimeInSeconds,
      remainingDistanceInMeters: remainingDistanceInMeters
    )
  }
  func toList() -> [Any?] {
    return [
      vehicleState,
      location,
      destinationWaypoint,
      route,
      remainingTimeInSeconds,
      remainingDistanceInMeters,
    ]
  }
  static func == (lhs: VehicleUpdateDto, rhs: VehicleUpdateDto) -> Bool {
    return deepEqualsmessages(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashmessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DriverApiTypeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VehicleStopStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VehicleStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DriverStatusLevelDto(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DriverStatusCodeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return TaskInfoDto.fromList(self.readValue() as! [Any?])
    case 135:
      return VehicleStopDto.fromList(self.readValue() as! [Any?])
    case 136:
      return LatLngDto.fromList(self.readValue() as! [Any?])
    case 137:
      return NavigationWaypointDto.fromList(self.readValue() as! [Any?])
    case 138:
      return LocationDto.fromList(self.readValue() as! [Any?])
    case 139:
      return DeliveryVehicleDto.fromList(self.readValue() as! [Any?])
    case 140:
      return VehicleUpdateDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DriverApiTypeDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? VehicleStopStateDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? VehicleStateDto {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? DriverStatusLevelDto {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? DriverStatusCodeDto {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? TaskInfoDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? VehicleStopDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? LatLngDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NavigationWaypointDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? LocationDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? DeliveryVehicleDto {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? VehicleUpdateDto {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CommonDriverApi {
  func initialize(
    type: DriverApiTypeDto, providerId: String, vehicleId: String,
    abnormalTerminationReportingEnabled: Bool) throws
  func isInitialized(type: DriverApiTypeDto) throws -> Bool
  func getProviderId(type: DriverApiTypeDto) throws -> String
  func getVehicleId(type: DriverApiTypeDto) throws -> String
  func isLocationTrackingEnabled(type: DriverApiTypeDto) throws -> Bool
  func setLocationTrackingEnabled(type: DriverApiTypeDto, enabled: Bool) throws
  func getLocationReportingIntervalMillis(type: DriverApiTypeDto) throws -> Int64
  func setLocationReportingIntervalMillis(type: DriverApiTypeDto, milliseconds: Int64) throws
  func dispose(type: DriverApiTypeDto) throws
  func getDriverSdkVersion(type: DriverApiTypeDto) throws -> String
  func setSupplementalLocation(type: DriverApiTypeDto, location: LocationDto) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CommonDriverApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CommonDriverApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: CommonDriverApi?,
    messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        let providerIdArg = args[1] as! String
        let vehicleIdArg = args[2] as! String
        let abnormalTerminationReportingEnabledArg = args[3] as! Bool
        do {
          try api.initialize(
            type: typeArg, providerId: providerIdArg, vehicleId: vehicleIdArg,
            abnormalTerminationReportingEnabled: abnormalTerminationReportingEnabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let isInitializedChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isInitializedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        do {
          let result = try api.isInitialized(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isInitializedChannel.setMessageHandler(nil)
    }
    let getProviderIdChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProviderIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        do {
          let result = try api.getProviderId(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getProviderIdChannel.setMessageHandler(nil)
    }
    let getVehicleIdChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVehicleIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        do {
          let result = try api.getVehicleId(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVehicleIdChannel.setMessageHandler(nil)
    }
    let isLocationTrackingEnabledChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isLocationTrackingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        do {
          let result = try api.isLocationTrackingEnabled(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isLocationTrackingEnabledChannel.setMessageHandler(nil)
    }
    let setLocationTrackingEnabledChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLocationTrackingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        let enabledArg = args[1] as! Bool
        do {
          try api.setLocationTrackingEnabled(type: typeArg, enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLocationTrackingEnabledChannel.setMessageHandler(nil)
    }
    let getLocationReportingIntervalMillisChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLocationReportingIntervalMillisChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        do {
          let result = try api.getLocationReportingIntervalMillis(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLocationReportingIntervalMillisChannel.setMessageHandler(nil)
    }
    let setLocationReportingIntervalMillisChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLocationReportingIntervalMillisChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        let millisecondsArg = args[1] as! Int64
        do {
          try api.setLocationReportingIntervalMillis(type: typeArg, milliseconds: millisecondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLocationReportingIntervalMillisChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        do {
          try api.dispose(type: typeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let getDriverSdkVersionChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDriverSdkVersionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        do {
          let result = try api.getDriverSdkVersion(type: typeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDriverSdkVersionChannel.setMessageHandler(nil)
    }
    let setSupplementalLocationChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSupplementalLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = args[0] as! DriverApiTypeDto
        let locationArg = args[1] as! LocationDto
        do {
          try api.setSupplementalLocation(type: typeArg, location: locationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSupplementalLocationChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeliveryDriverApi {
  func arrivedAtStop(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func completedStop(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func enrouteToNextStop(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func getRemainingVehicleStops(completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func setVehicleStops(
    stops: [VehicleStopDto], completion: @escaping (Result<[VehicleStopDto], Error>) -> Void)
  func getDeliveryVehicle(completion: @escaping (Result<DeliveryVehicleDto, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeliveryDriverApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DeliveryDriverApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: DeliveryDriverApi?,
    messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let arrivedAtStopChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.arrivedAtStop\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      arrivedAtStopChannel.setMessageHandler { _, reply in
        api.arrivedAtStop { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      arrivedAtStopChannel.setMessageHandler(nil)
    }
    let completedStopChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.completedStop\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      completedStopChannel.setMessageHandler { _, reply in
        api.completedStop { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      completedStopChannel.setMessageHandler(nil)
    }
    let enrouteToNextStopChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.enrouteToNextStop\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enrouteToNextStopChannel.setMessageHandler { _, reply in
        api.enrouteToNextStop { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enrouteToNextStopChannel.setMessageHandler(nil)
    }
    let getRemainingVehicleStopsChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getRemainingVehicleStops\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRemainingVehicleStopsChannel.setMessageHandler { _, reply in
        api.getRemainingVehicleStops { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getRemainingVehicleStopsChannel.setMessageHandler(nil)
    }
    let setVehicleStopsChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVehicleStopsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stopsArg = args[0] as! [VehicleStopDto]
        api.setVehicleStops(stops: stopsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setVehicleStopsChannel.setMessageHandler(nil)
    }
    let getDeliveryVehicleChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getDeliveryVehicle\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeliveryVehicleChannel.setMessageHandler { _, reply in
        api.getDeliveryVehicle { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeliveryVehicleChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RidesharingDriverApi {
  func setVehicleState(state: VehicleStateDto) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RidesharingDriverApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `RidesharingDriverApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: RidesharingDriverApi?,
    messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setVehicleStateChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVehicleStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = args[0] as! VehicleStateDto
        do {
          try api.setVehicleState(state: stateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVehicleStateChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AuthTokenEventApiProtocol {
  func getToken(
    taskId taskIdArg: String?, vehicleId vehicleIdArg: String?,
    completion: @escaping (Result<String, PigeonError>) -> Void)
}
class AuthTokenEventApi: AuthTokenEventApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func getToken(
    taskId taskIdArg: String?, vehicleId vehicleIdArg: String?,
    completion: @escaping (Result<String, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([taskIdArg, vehicleIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! String
        completion(.success(result))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VehicleReporterListenerApiProtocol {
  func onDidSucceed(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto,
    completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDidFail(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto, errorCode errorCodeArg: String,
    errorMessage errorMessageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class VehicleReporterListenerApi: VehicleReporterListenerApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onDidSucceed(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto,
    completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([vehicleUpdateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDidFail(
    vehicleUpdate vehicleUpdateArg: VehicleUpdateDto, errorCode errorCodeArg: String,
    errorMessage errorMessageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([vehicleUpdateArg, errorCodeArg, errorMessageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DriverStatusListenerApiProtocol {
  func onStatusUpdate(
    level levelArg: DriverStatusLevelDto, code codeArg: DriverStatusCodeDto,
    message messageArg: String, errorCode errorCodeArg: String?,
    errorMessage errorMessageArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void
  )
}
class DriverStatusListenerApi: DriverStatusListenerApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onStatusUpdate(
    level levelArg: DriverStatusLevelDto, code codeArg: DriverStatusCodeDto,
    message messageArg: String, errorCode errorCodeArg: String?,
    errorMessage errorMessageArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([levelArg, codeArg, messageArg, errorCodeArg, errorMessageArg] as [Any?]) {
      response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
