// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every((MapEntry<Object?, Object?> entry) =>
            (b as Map<Object?, Object?>).containsKey(entry.key) &&
            _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}

/// Indicates the API type for a driver.
enum DriverApiTypeDto {
  /// Indicates the API is for a delivery driver.
  delivery,

  /// Indicates the API is for a ridesharing driver.
  ridesharing,
}

enum VehicleStopStateDto {
  stateUnspecified,
  newStop,
  enroute,
  arrived,
}

enum VehicleStateDto {
  /// Indicates the vehicle is not accepting new trips.
  offline,

  /// Indicates the vehicle is accepting new trips.
  online,
}

enum DriverStatusLevelDto {
  debug,
  info,
  warning,
  error,
}

enum DriverStatusCodeDto {
  defaultStatus,
  unknownError,
  vehicleNotFound,
  backendConnectivityError,
  permissionDenied,
  serviceError,
  fileAccessError,
  traveledRouteError,
}

class TaskInfoDto {
  TaskInfoDto({
    required this.taskId,
    required this.durationSeconds,
  });

  String taskId;

  int durationSeconds;

  List<Object?> _toList() {
    return <Object?>[
      taskId,
      durationSeconds,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TaskInfoDto decode(Object result) {
    result as List<Object?>;
    return TaskInfoDto(
      taskId: result[0]! as String,
      durationSeconds: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TaskInfoDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class VehicleStopDto {
  VehicleStopDto({
    required this.vehicleStopState,
    this.waypoint,
    required this.taskInfoList,
  });

  VehicleStopStateDto vehicleStopState;

  NavigationWaypointDto? waypoint;

  List<TaskInfoDto?> taskInfoList;

  List<Object?> _toList() {
    return <Object?>[
      vehicleStopState,
      waypoint,
      taskInfoList,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VehicleStopDto decode(Object result) {
    result as List<Object?>;
    return VehicleStopDto(
      vehicleStopState: result[0]! as VehicleStopStateDto,
      waypoint: result[1] as NavigationWaypointDto?,
      taskInfoList: (result[2] as List<Object?>?)!.cast<TaskInfoDto?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VehicleStopDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LatLngDto {
  LatLngDto({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LatLngDto decode(Object result) {
    result as List<Object?>;
    return LatLngDto(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LatLngDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class NavigationWaypointDto {
  NavigationWaypointDto({
    required this.title,
    this.target,
    this.placeID,
    this.preferSameSideOfRoad,
    this.preferredSegmentHeading,
  });

  String title;

  LatLngDto? target;

  String? placeID;

  bool? preferSameSideOfRoad;

  int? preferredSegmentHeading;

  List<Object?> _toList() {
    return <Object?>[
      title,
      target,
      placeID,
      preferSameSideOfRoad,
      preferredSegmentHeading,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NavigationWaypointDto decode(Object result) {
    result as List<Object?>;
    return NavigationWaypointDto(
      title: result[0]! as String,
      target: result[1] as LatLngDto?,
      placeID: result[2] as String?,
      preferSameSideOfRoad: result[3] as bool?,
      preferredSegmentHeading: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavigationWaypointDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LocationDto {
  LocationDto({
    this.accuracy,
    this.altitude,
    this.elapsedRealtimeNanos,
    this.bearing,
    this.isMock,
    this.latitude,
    this.longitude,
    this.provider,
    this.speed,
    this.time,
  });

  double? accuracy;

  double? altitude;

  int? elapsedRealtimeNanos;

  double? bearing;

  bool? isMock;

  double? latitude;

  double? longitude;

  String? provider;

  double? speed;

  int? time;

  List<Object?> _toList() {
    return <Object?>[
      accuracy,
      altitude,
      elapsedRealtimeNanos,
      bearing,
      isMock,
      latitude,
      longitude,
      provider,
      speed,
      time,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LocationDto decode(Object result) {
    result as List<Object?>;
    return LocationDto(
      accuracy: result[0] as double?,
      altitude: result[1] as double?,
      elapsedRealtimeNanos: result[2] as int?,
      bearing: result[3] as double?,
      isMock: result[4] as bool?,
      latitude: result[5] as double?,
      longitude: result[6] as double?,
      provider: result[7] as String?,
      speed: result[8] as double?,
      time: result[9] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocationDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class DeliveryVehicleDto {
  DeliveryVehicleDto({
    required this.providerId,
    required this.id,
    required this.name,
    required this.stops,
  });

  String providerId;

  String id;

  String name;

  List<VehicleStopDto?> stops;

  List<Object?> _toList() {
    return <Object?>[
      providerId,
      id,
      name,
      stops,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DeliveryVehicleDto decode(Object result) {
    result as List<Object?>;
    return DeliveryVehicleDto(
      providerId: result[0]! as String,
      id: result[1]! as String,
      name: result[2]! as String,
      stops: (result[3] as List<Object?>?)!.cast<VehicleStopDto?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeliveryVehicleDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class VehicleUpdateDto {
  VehicleUpdateDto({
    this.vehicleState,
    this.location,
    this.destinationWaypoint,
    this.route,
    this.remainingTimeInSeconds,
    this.remainingDistanceInMeters,
  });

  VehicleStateDto? vehicleState;

  LatLngDto? location;

  NavigationWaypointDto? destinationWaypoint;

  List<LatLngDto?>? route;

  double? remainingTimeInSeconds;

  double? remainingDistanceInMeters;

  List<Object?> _toList() {
    return <Object?>[
      vehicleState,
      location,
      destinationWaypoint,
      route,
      remainingTimeInSeconds,
      remainingDistanceInMeters,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VehicleUpdateDto decode(Object result) {
    result as List<Object?>;
    return VehicleUpdateDto(
      vehicleState: result[0] as VehicleStateDto?,
      location: result[1] as LatLngDto?,
      destinationWaypoint: result[2] as NavigationWaypointDto?,
      route: (result[3] as List<Object?>?)?.cast<LatLngDto?>(),
      remainingTimeInSeconds: result[4] as double?,
      remainingDistanceInMeters: result[5] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VehicleUpdateDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is DriverApiTypeDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is VehicleStopStateDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is VehicleStateDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is DriverStatusLevelDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is DriverStatusCodeDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is TaskInfoDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is VehicleStopDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is LatLngDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is NavigationWaypointDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is LocationDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is DeliveryVehicleDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is VehicleUpdateDto) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DriverApiTypeDto.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VehicleStopStateDto.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VehicleStateDto.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DriverStatusLevelDto.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DriverStatusCodeDto.values[value];
      case 134:
        return TaskInfoDto.decode(readValue(buffer)!);
      case 135:
        return VehicleStopDto.decode(readValue(buffer)!);
      case 136:
        return LatLngDto.decode(readValue(buffer)!);
      case 137:
        return NavigationWaypointDto.decode(readValue(buffer)!);
      case 138:
        return LocationDto.decode(readValue(buffer)!);
      case 139:
        return DeliveryVehicleDto.decode(readValue(buffer)!);
      case 140:
        return VehicleUpdateDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CommonDriverApi {
  /// Constructor for [CommonDriverApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CommonDriverApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(DriverApiTypeDto type, String providerId,
      String vehicleId, bool abnormalTerminationReportingEnabled) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel
        .send(<Object?>[
      type,
      providerId,
      vehicleId,
      abnormalTerminationReportingEnabled
    ]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isInitialized(DriverApiTypeDto type) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<String> getProviderId(DriverApiTypeDto type) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> getVehicleId(DriverApiTypeDto type) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<bool> isLocationTrackingEnabled(DriverApiTypeDto type) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> setLocationTrackingEnabled(
      DriverApiTypeDto type, bool enabled) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type, enabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> getLocationReportingIntervalMillis(DriverApiTypeDto type) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> setLocationReportingIntervalMillis(
      DriverApiTypeDto type, int milliseconds) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type, milliseconds]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> dispose(DriverApiTypeDto type) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> getDriverSdkVersion(DriverApiTypeDto type) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> setSupplementalLocation(
      DriverApiTypeDto type, LocationDto location) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[type, location]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

class DeliveryDriverApi {
  /// Constructor for [DeliveryDriverApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeliveryDriverApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<VehicleStopDto>> arrivedAtStop() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.arrivedAtStop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<VehicleStopDto>();
    }
  }

  Future<List<VehicleStopDto>> completedStop() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.completedStop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<VehicleStopDto>();
    }
  }

  Future<List<VehicleStopDto>> enrouteToNextStop() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.enrouteToNextStop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<VehicleStopDto>();
    }
  }

  Future<List<VehicleStopDto>> getRemainingVehicleStops() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getRemainingVehicleStops$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<VehicleStopDto>();
    }
  }

  Future<List<VehicleStopDto>> setVehicleStops(
      List<VehicleStopDto> stops) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[stops]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<VehicleStopDto>();
    }
  }

  Future<DeliveryVehicleDto> getDeliveryVehicle() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getDeliveryVehicle$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DeliveryVehicleDto?)!;
    }
  }
}

class RidesharingDriverApi {
  /// Constructor for [RidesharingDriverApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RidesharingDriverApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setVehicleState(VehicleStateDto state) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[state]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class AuthTokenEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<String> getToken(String? taskId, String? vehicleId);

  static void setUp(
    AuthTokenEventApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_taskId = (args[0] as String?);
          final String? arg_vehicleId = (args[1] as String?);
          try {
            final String output = await api.getToken(arg_taskId, arg_vehicleId);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

abstract class VehicleReporterListenerApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onDidSucceed(VehicleUpdateDto vehicleUpdate);

  void onDidFail(
      VehicleUpdateDto vehicleUpdate, String errorCode, String errorMessage);

  static void setUp(
    VehicleReporterListenerApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final VehicleUpdateDto? arg_vehicleUpdate =
              (args[0] as VehicleUpdateDto?);
          assert(arg_vehicleUpdate != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed was null, expected non-null VehicleUpdateDto.');
          try {
            api.onDidSucceed(arg_vehicleUpdate!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final VehicleUpdateDto? arg_vehicleUpdate =
              (args[0] as VehicleUpdateDto?);
          assert(arg_vehicleUpdate != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null, expected non-null VehicleUpdateDto.');
          final String? arg_errorCode = (args[1] as String?);
          assert(arg_errorCode != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null, expected non-null String.');
          final String? arg_errorMessage = (args[2] as String?);
          assert(arg_errorMessage != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null, expected non-null String.');
          try {
            api.onDidFail(
                arg_vehicleUpdate!, arg_errorCode!, arg_errorMessage!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

abstract class DriverStatusListenerApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStatusUpdate(DriverStatusLevelDto level, DriverStatusCodeDto code,
      String message, String? errorCode, String? errorMessage);

  static void setUp(
    DriverStatusListenerApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DriverStatusLevelDto? arg_level =
              (args[0] as DriverStatusLevelDto?);
          assert(arg_level != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null, expected non-null DriverStatusLevelDto.');
          final DriverStatusCodeDto? arg_code =
              (args[1] as DriverStatusCodeDto?);
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null, expected non-null DriverStatusCodeDto.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null, expected non-null String.');
          final String? arg_errorCode = (args[3] as String?);
          final String? arg_errorMessage = (args[4] as String?);
          try {
            api.onStatusUpdate(arg_level!, arg_code!, arg_message!,
                arg_errorCode, arg_errorMessage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
