// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Autogenerated from Pigeon (v15.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Indicates the API type for a driver.
enum DriverApiTypeDto {
  /// Indicates the API is for a delivery driver.
  delivery,

  /// Indicates the API is for a ridesharing driver.
  ridesharing,
}

enum VehicleStopStateDto {
  stateUnspecified,
  newStop,
  enroute,
  arrived,
}

enum VehicleStateDto {
  /// Indicates the vehicle is not accepting new trips.
  offline,

  /// Indicates the vehicle is accepting new trips.
  online,
}

enum DriverStatusLevelDto {
  debug,
  info,
  warning,
  error,
}

enum DriverStatusCodeDto {
  defaultStatus,
  unknownError,
  vehicleNotFound,
  backendConnectivityError,
  permissionDenied,
  serviceError,
  fileAccessError,
  traveledRouteError,
}

class TaskInfoDto {
  TaskInfoDto({
    required this.taskId,
    required this.durationSeconds,
  });

  String taskId;

  int durationSeconds;

  Object encode() {
    return <Object?>[
      taskId,
      durationSeconds,
    ];
  }

  static TaskInfoDto decode(Object result) {
    result as List<Object?>;
    return TaskInfoDto(
      taskId: result[0]! as String,
      durationSeconds: result[1]! as int,
    );
  }
}

class VehicleStopDto {
  VehicleStopDto({
    required this.vehicleStopState,
    this.waypoint,
    required this.taskInfoList,
  });

  VehicleStopStateDto vehicleStopState;

  NavigationWaypointDto? waypoint;

  List<TaskInfoDto?> taskInfoList;

  Object encode() {
    return <Object?>[
      vehicleStopState.index,
      waypoint?.encode(),
      taskInfoList,
    ];
  }

  static VehicleStopDto decode(Object result) {
    result as List<Object?>;
    return VehicleStopDto(
      vehicleStopState: VehicleStopStateDto.values[result[0]! as int],
      waypoint: result[1] != null
          ? NavigationWaypointDto.decode(result[1]! as List<Object?>)
          : null,
      taskInfoList: (result[2] as List<Object?>?)!.cast<TaskInfoDto?>(),
    );
  }
}

class LatLngDto {
  LatLngDto({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  Object encode() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  static LatLngDto decode(Object result) {
    result as List<Object?>;
    return LatLngDto(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }
}

class NavigationWaypointDto {
  NavigationWaypointDto({
    required this.title,
    this.target,
    this.placeID,
    this.preferSameSideOfRoad,
    this.preferredSegmentHeading,
  });

  String title;

  LatLngDto? target;

  String? placeID;

  bool? preferSameSideOfRoad;

  int? preferredSegmentHeading;

  Object encode() {
    return <Object?>[
      title,
      target?.encode(),
      placeID,
      preferSameSideOfRoad,
      preferredSegmentHeading,
    ];
  }

  static NavigationWaypointDto decode(Object result) {
    result as List<Object?>;
    return NavigationWaypointDto(
      title: result[0]! as String,
      target: result[1] != null
          ? LatLngDto.decode(result[1]! as List<Object?>)
          : null,
      placeID: result[2] as String?,
      preferSameSideOfRoad: result[3] as bool?,
      preferredSegmentHeading: result[4] as int?,
    );
  }
}

class LocationDto {
  LocationDto({
    this.accuracy,
    this.altitude,
    this.elapsedRealtimeNanos,
    this.bearing,
    this.isMock,
    this.latitude,
    this.longitude,
    this.provider,
    this.speed,
    this.time,
  });

  double? accuracy;

  double? altitude;

  int? elapsedRealtimeNanos;

  double? bearing;

  bool? isMock;

  double? latitude;

  double? longitude;

  String? provider;

  double? speed;

  int? time;

  Object encode() {
    return <Object?>[
      accuracy,
      altitude,
      elapsedRealtimeNanos,
      bearing,
      isMock,
      latitude,
      longitude,
      provider,
      speed,
      time,
    ];
  }

  static LocationDto decode(Object result) {
    result as List<Object?>;
    return LocationDto(
      accuracy: result[0] as double?,
      altitude: result[1] as double?,
      elapsedRealtimeNanos: result[2] as int?,
      bearing: result[3] as double?,
      isMock: result[4] as bool?,
      latitude: result[5] as double?,
      longitude: result[6] as double?,
      provider: result[7] as String?,
      speed: result[8] as double?,
      time: result[9] as int?,
    );
  }
}

class DeliveryVehicleDto {
  DeliveryVehicleDto({
    required this.providerId,
    required this.id,
    required this.name,
    required this.stops,
  });

  String providerId;

  String id;

  String name;

  List<VehicleStopDto?> stops;

  Object encode() {
    return <Object?>[
      providerId,
      id,
      name,
      stops,
    ];
  }

  static DeliveryVehicleDto decode(Object result) {
    result as List<Object?>;
    return DeliveryVehicleDto(
      providerId: result[0]! as String,
      id: result[1]! as String,
      name: result[2]! as String,
      stops: (result[3] as List<Object?>?)!.cast<VehicleStopDto?>(),
    );
  }
}

class VehicleUpdateDto {
  VehicleUpdateDto({
    this.vehicleState,
    this.location,
    this.destinationWaypoint,
    this.route,
    this.remainingTimeInSeconds,
    this.remainingDistanceInMeters,
  });

  VehicleStateDto? vehicleState;

  LatLngDto? location;

  NavigationWaypointDto? destinationWaypoint;

  List<LatLngDto?>? route;

  double? remainingTimeInSeconds;

  double? remainingDistanceInMeters;

  Object encode() {
    return <Object?>[
      vehicleState?.index,
      location?.encode(),
      destinationWaypoint?.encode(),
      route,
      remainingTimeInSeconds,
      remainingDistanceInMeters,
    ];
  }

  static VehicleUpdateDto decode(Object result) {
    result as List<Object?>;
    return VehicleUpdateDto(
      vehicleState:
          result[0] != null ? VehicleStateDto.values[result[0]! as int] : null,
      location: result[1] != null
          ? LatLngDto.decode(result[1]! as List<Object?>)
          : null,
      destinationWaypoint: result[2] != null
          ? NavigationWaypointDto.decode(result[2]! as List<Object?>)
          : null,
      route: (result[3] as List<Object?>?)?.cast<LatLngDto?>(),
      remainingTimeInSeconds: result[4] as double?,
      remainingDistanceInMeters: result[5] as double?,
    );
  }
}

class _CommonDriverApiCodec extends StandardMessageCodec {
  const _CommonDriverApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LocationDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return LocationDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CommonDriverApi {
  /// Constructor for [CommonDriverApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CommonDriverApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec =
      _CommonDriverApiCodec();

  Future<void> initialize(DriverApiTypeDto type, String providerId,
      String vehicleId, bool abnormalTerminationReportingEnabled) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList = await __pigeon_channel
        .send(<Object?>[
      type.index,
      providerId,
      vehicleId,
      abnormalTerminationReportingEnabled
    ]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isInitialized(DriverApiTypeDto type) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[type.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<String> getProviderId(DriverApiTypeDto type) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[type.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  Future<String> getVehicleId(DriverApiTypeDto type) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[type.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  Future<bool> isLocationTrackingEnabled(DriverApiTypeDto type) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[type.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<void> setLocationTrackingEnabled(
      DriverApiTypeDto type, bool enabled) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList = await __pigeon_channel
        .send(<Object?>[type.index, enabled]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> getLocationReportingIntervalMillis(DriverApiTypeDto type) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[type.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  Future<void> setLocationReportingIntervalMillis(
      DriverApiTypeDto type, int milliseconds) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList = await __pigeon_channel
        .send(<Object?>[type.index, milliseconds]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> dispose(DriverApiTypeDto type) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[type.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> getDriverSdkVersion(DriverApiTypeDto type) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[type.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  Future<void> setSupplementalLocation(
      DriverApiTypeDto type, LocationDto location) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList = await __pigeon_channel
        .send(<Object?>[type.index, location]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

class _DeliveryDriverApiCodec extends StandardMessageCodec {
  const _DeliveryDriverApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is DeliveryVehicleDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is LatLngDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NavigationWaypointDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is TaskInfoDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is VehicleStopDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return DeliveryVehicleDto.decode(readValue(buffer)!);
      case 129:
        return LatLngDto.decode(readValue(buffer)!);
      case 130:
        return NavigationWaypointDto.decode(readValue(buffer)!);
      case 131:
        return TaskInfoDto.decode(readValue(buffer)!);
      case 132:
        return VehicleStopDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DeliveryDriverApi {
  /// Constructor for [DeliveryDriverApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeliveryDriverApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec =
      _DeliveryDriverApiCodec();

  Future<List<VehicleStopDto?>> arrivedAtStop() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.arrivedAtStop';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<VehicleStopDto?>();
    }
  }

  Future<List<VehicleStopDto?>> completedStop() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.completedStop';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<VehicleStopDto?>();
    }
  }

  Future<List<VehicleStopDto?>> enrouteToNextStop() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.enrouteToNextStop';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<VehicleStopDto?>();
    }
  }

  Future<List<VehicleStopDto?>> getRemainingVehicleStops() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getRemainingVehicleStops';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<VehicleStopDto?>();
    }
  }

  Future<List<VehicleStopDto?>> setVehicleStops(
      List<VehicleStopDto?> stops) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[stops]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<VehicleStopDto?>();
    }
  }

  Future<DeliveryVehicleDto> getDeliveryVehicle() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getDeliveryVehicle';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as DeliveryVehicleDto?)!;
    }
  }
}

class RidesharingDriverApi {
  /// Constructor for [RidesharingDriverApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RidesharingDriverApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec =
      StandardMessageCodec();

  Future<void> setVehicleState(VehicleStateDto state) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[state.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class AuthTokenEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec =
      StandardMessageCodec();

  Future<String> getToken(String? taskId, String? vehicleId);

  static void setup(AuthTokenEventApi? api,
      {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_taskId = (args[0] as String?);
          final String? arg_vehicleId = (args[1] as String?);
          try {
            final String output = await api.getToken(arg_taskId, arg_vehicleId);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class _VehicleReporterListenerApiCodec extends StandardMessageCodec {
  const _VehicleReporterListenerApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LatLngDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is LatLngDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NavigationWaypointDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is VehicleUpdateDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return LatLngDto.decode(readValue(buffer)!);
      case 129:
        return LatLngDto.decode(readValue(buffer)!);
      case 130:
        return NavigationWaypointDto.decode(readValue(buffer)!);
      case 131:
        return VehicleUpdateDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class VehicleReporterListenerApi {
  static const MessageCodec<Object?> pigeonChannelCodec =
      _VehicleReporterListenerApiCodec();

  void onDidSucceed(VehicleUpdateDto vehicleUpdate);

  void onDidFail(
      VehicleUpdateDto vehicleUpdate, String errorCode, String errorMessage);

  static void setup(VehicleReporterListenerApi? api,
      {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final VehicleUpdateDto? arg_vehicleUpdate =
              (args[0] as VehicleUpdateDto?);
          assert(arg_vehicleUpdate != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed was null, expected non-null VehicleUpdateDto.');
          try {
            api.onDidSucceed(arg_vehicleUpdate!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final VehicleUpdateDto? arg_vehicleUpdate =
              (args[0] as VehicleUpdateDto?);
          assert(arg_vehicleUpdate != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null, expected non-null VehicleUpdateDto.');
          final String? arg_errorCode = (args[1] as String?);
          assert(arg_errorCode != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null, expected non-null String.');
          final String? arg_errorMessage = (args[2] as String?);
          assert(arg_errorMessage != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail was null, expected non-null String.');
          try {
            api.onDidFail(
                arg_vehicleUpdate!, arg_errorCode!, arg_errorMessage!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

abstract class DriverStatusListenerApi {
  static const MessageCodec<Object?> pigeonChannelCodec =
      StandardMessageCodec();

  void onStatusUpdate(DriverStatusLevelDto level, DriverStatusCodeDto code,
      String message, String? errorCode, String? errorMessage);

  static void setup(DriverStatusListenerApi? api,
      {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DriverStatusLevelDto? arg_level = args[0] == null
              ? null
              : DriverStatusLevelDto.values[args[0]! as int];
          assert(arg_level != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null, expected non-null DriverStatusLevelDto.');
          final DriverStatusCodeDto? arg_code = args[1] == null
              ? null
              : DriverStatusCodeDto.values[args[1]! as int];
          assert(arg_code != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null, expected non-null DriverStatusCodeDto.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate was null, expected non-null String.');
          final String? arg_errorCode = (args[3] as String?);
          final String? arg_errorMessage = (args[4] as String?);
          try {
            api.onStatusUpdate(arg_level!, arg_code!, arg_message!,
                arg_errorCode, arg_errorMessage);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
