// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Autogenerated from Pigeon (v15.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.google.maps.flutter.driver

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(exception.code, exception.message, exception.details)
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError(
    "channel-error",
    "Unable to establish connection on channel: '$channelName'.",
    "",
  )
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
  val code: String,
  override val message: String? = null,
  val details: Any? = null,
) : Throwable()

/** Indicates the API type for a driver. */
enum class DriverApiTypeDto(val raw: Int) {
  /** Indicates the API is for a delivery driver. */
  DELIVERY(0),
  /** Indicates the API is for a ridesharing driver. */
  RIDESHARING(1);

  companion object {
    fun ofRaw(raw: Int): DriverApiTypeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VehicleStopStateDto(val raw: Int) {
  STATEUNSPECIFIED(0),
  NEWSTOP(1),
  ENROUTE(2),
  ARRIVED(3);

  companion object {
    fun ofRaw(raw: Int): VehicleStopStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VehicleStateDto(val raw: Int) {
  /** Indicates the vehicle is not accepting new trips. */
  OFFLINE(0),
  /** Indicates the vehicle is accepting new trips. */
  ONLINE(1);

  companion object {
    fun ofRaw(raw: Int): VehicleStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DriverStatusLevelDto(val raw: Int) {
  DEBUG(0),
  INFO(1),
  WARNING(2),
  ERROR(3);

  companion object {
    fun ofRaw(raw: Int): DriverStatusLevelDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DriverStatusCodeDto(val raw: Int) {
  DEFAULTSTATUS(0),
  UNKNOWNERROR(1),
  VEHICLENOTFOUND(2),
  BACKENDCONNECTIVITYERROR(3),
  PERMISSIONDENIED(4),
  SERVICEERROR(5),
  FILEACCESSERROR(6),
  TRAVELEDROUTEERROR(7);

  companion object {
    fun ofRaw(raw: Int): DriverStatusCodeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TaskInfoDto(val taskId: String, val durationSeconds: Long) {

  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TaskInfoDto {
      val taskId = list[0] as String
      val durationSeconds = list[1].let { if (it is Int) it.toLong() else it as Long }
      return TaskInfoDto(taskId, durationSeconds)
    }
  }

  fun toList(): List<Any?> {
    return listOf<Any?>(taskId, durationSeconds)
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VehicleStopDto(
  val vehicleStopState: VehicleStopStateDto,
  val waypoint: NavigationWaypointDto? = null,
  val taskInfoList: List<TaskInfoDto?>,
) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): VehicleStopDto {
      val vehicleStopState = VehicleStopStateDto.ofRaw(list[0] as Int)!!
      val waypoint: NavigationWaypointDto? =
        (list[1] as List<Any?>?)?.let { NavigationWaypointDto.fromList(it) }
      val taskInfoList = list[2] as List<TaskInfoDto?>
      return VehicleStopDto(vehicleStopState, waypoint, taskInfoList)
    }
  }

  fun toList(): List<Any?> {
    return listOf<Any?>(vehicleStopState.raw, waypoint?.toList(), taskInfoList)
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LatLngDto(val latitude: Double, val longitude: Double) {

  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): LatLngDto {
      val latitude = list[0] as Double
      val longitude = list[1] as Double
      return LatLngDto(latitude, longitude)
    }
  }

  fun toList(): List<Any?> {
    return listOf<Any?>(latitude, longitude)
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NavigationWaypointDto(
  val title: String,
  val target: LatLngDto? = null,
  val placeID: String? = null,
  val preferSameSideOfRoad: Boolean? = null,
  val preferredSegmentHeading: Long? = null,
) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): NavigationWaypointDto {
      val title = list[0] as String
      val target: LatLngDto? = (list[1] as List<Any?>?)?.let { LatLngDto.fromList(it) }
      val placeID = list[2] as String?
      val preferSameSideOfRoad = list[3] as Boolean?
      val preferredSegmentHeading = list[4].let { if (it is Int) it.toLong() else it as Long? }
      return NavigationWaypointDto(
        title,
        target,
        placeID,
        preferSameSideOfRoad,
        preferredSegmentHeading,
      )
    }
  }

  fun toList(): List<Any?> {
    return listOf<Any?>(
      title,
      target?.toList(),
      placeID,
      preferSameSideOfRoad,
      preferredSegmentHeading,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocationDto(
  val accuracy: Double? = null,
  val altitude: Double? = null,
  val elapsedRealtimeNanos: Long? = null,
  val bearing: Double? = null,
  val isMock: Boolean? = null,
  val latitude: Double? = null,
  val longitude: Double? = null,
  val provider: String? = null,
  val speed: Double? = null,
  val time: Long? = null,
) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): LocationDto {
      val accuracy = list[0] as Double?
      val altitude = list[1] as Double?
      val elapsedRealtimeNanos = list[2].let { if (it is Int) it.toLong() else it as Long? }
      val bearing = list[3] as Double?
      val isMock = list[4] as Boolean?
      val latitude = list[5] as Double?
      val longitude = list[6] as Double?
      val provider = list[7] as String?
      val speed = list[8] as Double?
      val time = list[9].let { if (it is Int) it.toLong() else it as Long? }
      return LocationDto(
        accuracy,
        altitude,
        elapsedRealtimeNanos,
        bearing,
        isMock,
        latitude,
        longitude,
        provider,
        speed,
        time,
      )
    }
  }

  fun toList(): List<Any?> {
    return listOf<Any?>(
      accuracy,
      altitude,
      elapsedRealtimeNanos,
      bearing,
      isMock,
      latitude,
      longitude,
      provider,
      speed,
      time,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeliveryVehicleDto(
  val providerId: String,
  val id: String,
  val name: String,
  val stops: List<VehicleStopDto?>,
) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DeliveryVehicleDto {
      val providerId = list[0] as String
      val id = list[1] as String
      val name = list[2] as String
      val stops = list[3] as List<VehicleStopDto?>
      return DeliveryVehicleDto(providerId, id, name, stops)
    }
  }

  fun toList(): List<Any?> {
    return listOf<Any?>(providerId, id, name, stops)
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VehicleUpdateDto(
  val vehicleState: VehicleStateDto? = null,
  val location: LatLngDto? = null,
  val destinationWaypoint: NavigationWaypointDto? = null,
  val route: List<LatLngDto?>? = null,
  val remainingTimeInSeconds: Double? = null,
  val remainingDistanceInMeters: Double? = null,
) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): VehicleUpdateDto {
      val vehicleState: VehicleStateDto? = (list[0] as Int?)?.let { VehicleStateDto.ofRaw(it) }
      val location: LatLngDto? = (list[1] as List<Any?>?)?.let { LatLngDto.fromList(it) }
      val destinationWaypoint: NavigationWaypointDto? =
        (list[2] as List<Any?>?)?.let { NavigationWaypointDto.fromList(it) }
      val route = list[3] as List<LatLngDto?>?
      val remainingTimeInSeconds = list[4] as Double?
      val remainingDistanceInMeters = list[5] as Double?
      return VehicleUpdateDto(
        vehicleState,
        location,
        destinationWaypoint,
        route,
        remainingTimeInSeconds,
        remainingDistanceInMeters,
      )
    }
  }

  fun toList(): List<Any?> {
    return listOf<Any?>(
      vehicleState?.raw,
      location?.toList(),
      destinationWaypoint?.toList(),
      route,
      remainingTimeInSeconds,
      remainingDistanceInMeters,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object CommonDriverApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { LocationDto.fromList(it) }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is LocationDto -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CommonDriverApi {
  fun initialize(
    type: DriverApiTypeDto,
    providerId: String,
    vehicleId: String,
    abnormalTerminationReportingEnabled: Boolean,
  )

  fun isInitialized(type: DriverApiTypeDto): Boolean

  fun getProviderId(type: DriverApiTypeDto): String

  fun getVehicleId(type: DriverApiTypeDto): String

  fun isLocationTrackingEnabled(type: DriverApiTypeDto): Boolean

  fun setLocationTrackingEnabled(type: DriverApiTypeDto, enabled: Boolean)

  fun getLocationReportingIntervalMillis(type: DriverApiTypeDto): Long

  fun setLocationReportingIntervalMillis(type: DriverApiTypeDto, milliseconds: Long)

  fun dispose(type: DriverApiTypeDto)

  fun getDriverSdkVersion(type: DriverApiTypeDto): String

  fun setSupplementalLocation(type: DriverApiTypeDto, location: LocationDto)

  companion object {
    /** The codec used by CommonDriverApi. */
    val codec: MessageCodec<Any?> by lazy { CommonDriverApiCodec }

    /**
     * Sets up an instance of `CommonDriverApi` to handle messages through the `binaryMessenger`.
     */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: CommonDriverApi?) {
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            val providerIdArg = args[1] as String
            val vehicleIdArg = args[2] as String
            val abnormalTerminationReportingEnabledArg = args[3] as Boolean
            var wrapped: List<Any?>
            try {
              api.initialize(
                typeArg,
                providerIdArg,
                vehicleIdArg,
                abnormalTerminationReportingEnabledArg,
              )
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.isInitialized(typeArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getProviderId(typeArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getVehicleId(typeArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.isLocationTrackingEnabled(typeArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            val enabledArg = args[1] as Boolean
            var wrapped: List<Any?>
            try {
              api.setLocationTrackingEnabled(typeArg, enabledArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getLocationReportingIntervalMillis(typeArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            val millisecondsArg = args[1].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.setLocationReportingIntervalMillis(typeArg, millisecondsArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              api.dispose(typeArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getDriverSdkVersion(typeArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = DriverApiTypeDto.ofRaw(args[0] as Int)!!
            val locationArg = args[1] as LocationDto
            var wrapped: List<Any?>
            try {
              api.setSupplementalLocation(typeArg, locationArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

@Suppress("UNCHECKED_CAST")
private object DeliveryDriverApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { DeliveryVehicleDto.fromList(it) }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { LatLngDto.fromList(it) }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { NavigationWaypointDto.fromList(it) }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { TaskInfoDto.fromList(it) }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { VehicleStopDto.fromList(it) }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is DeliveryVehicleDto -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is LatLngDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NavigationWaypointDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TaskInfoDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VehicleStopDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DeliveryDriverApi {
  fun arrivedAtStop(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun completedStop(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun enrouteToNextStop(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun getRemainingVehicleStops(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun setVehicleStops(stops: List<VehicleStopDto>, callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun getDeliveryVehicle(callback: (Result<DeliveryVehicleDto>) -> Unit)

  companion object {
    /** The codec used by DeliveryDriverApi. */
    val codec: MessageCodec<Any?> by lazy { DeliveryDriverApiCodec }

    /**
     * Sets up an instance of `DeliveryDriverApi` to handle messages through the `binaryMessenger`.
     */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: DeliveryDriverApi?) {
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.arrivedAtStop",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.arrivedAtStop() { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.completedStop",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.completedStop() { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.enrouteToNextStop",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.enrouteToNextStop() { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getRemainingVehicleStops",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRemainingVehicleStops() { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stopsArg = args[0] as List<VehicleStopDto>
            api.setVehicleStops(stopsArg) { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getDeliveryVehicle",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeliveryVehicle() { result: Result<DeliveryVehicleDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RidesharingDriverApi {
  fun setVehicleState(state: VehicleStateDto)

  companion object {
    /** The codec used by RidesharingDriverApi. */
    val codec: MessageCodec<Any?> by lazy { StandardMessageCodec() }

    /**
     * Sets up an instance of `RidesharingDriverApi` to handle messages through the
     * `binaryMessenger`.
     */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: RidesharingDriverApi?) {
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = VehicleStateDto.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              api.setVehicleState(stateArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class AuthTokenEventApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by AuthTokenEventApi. */
    val codec: MessageCodec<Any?> by lazy { StandardMessageCodec() }
  }

  fun getToken(taskIdArg: String?, vehicleIdArg: String?, callback: (Result<String>) -> Unit) {
    val channelName = "dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, vehicleIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(
            Result.failure(
              FlutterError(
                "null-error",
                "Flutter api returned null value for non-null return value.",
                "",
              )
            )
          )
        } else {
          val output = it[0] as String
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }
}

@Suppress("UNCHECKED_CAST")
private object VehicleReporterListenerApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { LatLngDto.fromList(it) }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { LatLngDto.fromList(it) }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { NavigationWaypointDto.fromList(it) }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { VehicleUpdateDto.fromList(it) }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is LatLngDto -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is LatLngDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NavigationWaypointDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VehicleUpdateDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class VehicleReporterListenerApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by VehicleReporterListenerApi. */
    val codec: MessageCodec<Any?> by lazy { VehicleReporterListenerApiCodec }
  }

  fun onDidSucceed(vehicleUpdateArg: VehicleUpdateDto, callback: (Result<Unit>) -> Unit) {
    val channelName =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(vehicleUpdateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }

  fun onDidFail(
    vehicleUpdateArg: VehicleUpdateDto,
    errorCodeArg: String,
    errorMessageArg: String,
    callback: (Result<Unit>) -> Unit,
  ) {
    val channelName =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(vehicleUpdateArg, errorCodeArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class DriverStatusListenerApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by DriverStatusListenerApi. */
    val codec: MessageCodec<Any?> by lazy { StandardMessageCodec() }
  }

  fun onStatusUpdate(
    levelArg: DriverStatusLevelDto,
    codeArg: DriverStatusCodeDto,
    messageArg: String,
    errorCodeArg: String?,
    errorMessageArg: String?,
    callback: (Result<Unit>) -> Unit,
  ) {
    val channelName =
      "dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(levelArg.raw, codeArg.raw, messageArg, errorCodeArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }
}
