// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.google.maps.flutter.driver

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '$channelName'.",
      "",
    )
  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(exception.code, exception.message, exception.details)
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
      )
    }
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size && a.indices.all { deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size && a.indices.all { deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size &&
        a.all { (b as Map<Any?, Any?>).containsKey(it.key) && deepEquals(it.value, b[it.key]) }
    }
    return a == b
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
  val code: String,
  override val message: String? = null,
  val details: Any? = null,
) : Throwable()

/** Indicates the API type for a driver. */
enum class DriverApiTypeDto(val raw: Int) {
  /** Indicates the API is for a delivery driver. */
  DELIVERY(0),
  /** Indicates the API is for a ridesharing driver. */
  RIDESHARING(1);

  companion object {
    fun ofRaw(raw: Int): DriverApiTypeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VehicleStopStateDto(val raw: Int) {
  STATE_UNSPECIFIED(0),
  NEW_STOP(1),
  ENROUTE(2),
  ARRIVED(3);

  companion object {
    fun ofRaw(raw: Int): VehicleStopStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VehicleStateDto(val raw: Int) {
  /** Indicates the vehicle is not accepting new trips. */
  OFFLINE(0),
  /** Indicates the vehicle is accepting new trips. */
  ONLINE(1);

  companion object {
    fun ofRaw(raw: Int): VehicleStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DriverStatusLevelDto(val raw: Int) {
  DEBUG(0),
  INFO(1),
  WARNING(2),
  ERROR(3);

  companion object {
    fun ofRaw(raw: Int): DriverStatusLevelDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DriverStatusCodeDto(val raw: Int) {
  DEFAULT_STATUS(0),
  UNKNOWN_ERROR(1),
  VEHICLE_NOT_FOUND(2),
  BACKEND_CONNECTIVITY_ERROR(3),
  PERMISSION_DENIED(4),
  SERVICE_ERROR(5),
  FILE_ACCESS_ERROR(6),
  TRAVELED_ROUTE_ERROR(7);

  companion object {
    fun ofRaw(raw: Int): DriverStatusCodeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TaskInfoDto(val taskId: String, val durationSeconds: Long) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TaskInfoDto {
      val taskId = pigeonVar_list[0] as String
      val durationSeconds = pigeonVar_list[1] as Long
      return TaskInfoDto(taskId, durationSeconds)
    }
  }

  fun toList(): List<Any?> {
    return listOf(taskId, durationSeconds)
  }

  override fun equals(other: Any?): Boolean {
    if (other !is TaskInfoDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())
  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VehicleStopDto(
  val vehicleStopState: VehicleStopStateDto,
  val waypoint: NavigationWaypointDto? = null,
  val taskInfoList: List<TaskInfoDto?>,
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VehicleStopDto {
      val vehicleStopState = pigeonVar_list[0] as VehicleStopStateDto
      val waypoint = pigeonVar_list[1] as NavigationWaypointDto?
      val taskInfoList = pigeonVar_list[2] as List<TaskInfoDto?>
      return VehicleStopDto(vehicleStopState, waypoint, taskInfoList)
    }
  }

  fun toList(): List<Any?> {
    return listOf(vehicleStopState, waypoint, taskInfoList)
  }

  override fun equals(other: Any?): Boolean {
    if (other !is VehicleStopDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())
  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LatLngDto(val latitude: Double, val longitude: Double) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LatLngDto {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return LatLngDto(latitude, longitude)
    }
  }

  fun toList(): List<Any?> {
    return listOf(latitude, longitude)
  }

  override fun equals(other: Any?): Boolean {
    if (other !is LatLngDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())
  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NavigationWaypointDto(
  val title: String,
  val target: LatLngDto? = null,
  val placeID: String? = null,
  val preferSameSideOfRoad: Boolean? = null,
  val preferredSegmentHeading: Long? = null,
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NavigationWaypointDto {
      val title = pigeonVar_list[0] as String
      val target = pigeonVar_list[1] as LatLngDto?
      val placeID = pigeonVar_list[2] as String?
      val preferSameSideOfRoad = pigeonVar_list[3] as Boolean?
      val preferredSegmentHeading = pigeonVar_list[4] as Long?
      return NavigationWaypointDto(
        title,
        target,
        placeID,
        preferSameSideOfRoad,
        preferredSegmentHeading,
      )
    }
  }

  fun toList(): List<Any?> {
    return listOf(title, target, placeID, preferSameSideOfRoad, preferredSegmentHeading)
  }

  override fun equals(other: Any?): Boolean {
    if (other !is NavigationWaypointDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())
  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocationDto(
  val accuracy: Double? = null,
  val altitude: Double? = null,
  val elapsedRealtimeNanos: Long? = null,
  val bearing: Double? = null,
  val isMock: Boolean? = null,
  val latitude: Double? = null,
  val longitude: Double? = null,
  val provider: String? = null,
  val speed: Double? = null,
  val time: Long? = null,
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationDto {
      val accuracy = pigeonVar_list[0] as Double?
      val altitude = pigeonVar_list[1] as Double?
      val elapsedRealtimeNanos = pigeonVar_list[2] as Long?
      val bearing = pigeonVar_list[3] as Double?
      val isMock = pigeonVar_list[4] as Boolean?
      val latitude = pigeonVar_list[5] as Double?
      val longitude = pigeonVar_list[6] as Double?
      val provider = pigeonVar_list[7] as String?
      val speed = pigeonVar_list[8] as Double?
      val time = pigeonVar_list[9] as Long?
      return LocationDto(
        accuracy,
        altitude,
        elapsedRealtimeNanos,
        bearing,
        isMock,
        latitude,
        longitude,
        provider,
        speed,
        time,
      )
    }
  }

  fun toList(): List<Any?> {
    return listOf(
      accuracy,
      altitude,
      elapsedRealtimeNanos,
      bearing,
      isMock,
      latitude,
      longitude,
      provider,
      speed,
      time,
    )
  }

  override fun equals(other: Any?): Boolean {
    if (other !is LocationDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())
  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeliveryVehicleDto(
  val providerId: String,
  val id: String,
  val name: String,
  val stops: List<VehicleStopDto?>,
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeliveryVehicleDto {
      val providerId = pigeonVar_list[0] as String
      val id = pigeonVar_list[1] as String
      val name = pigeonVar_list[2] as String
      val stops = pigeonVar_list[3] as List<VehicleStopDto?>
      return DeliveryVehicleDto(providerId, id, name, stops)
    }
  }

  fun toList(): List<Any?> {
    return listOf(providerId, id, name, stops)
  }

  override fun equals(other: Any?): Boolean {
    if (other !is DeliveryVehicleDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())
  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VehicleUpdateDto(
  val vehicleState: VehicleStateDto? = null,
  val location: LatLngDto? = null,
  val destinationWaypoint: NavigationWaypointDto? = null,
  val route: List<LatLngDto?>? = null,
  val remainingTimeInSeconds: Double? = null,
  val remainingDistanceInMeters: Double? = null,
) {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VehicleUpdateDto {
      val vehicleState = pigeonVar_list[0] as VehicleStateDto?
      val location = pigeonVar_list[1] as LatLngDto?
      val destinationWaypoint = pigeonVar_list[2] as NavigationWaypointDto?
      val route = pigeonVar_list[3] as List<LatLngDto?>?
      val remainingTimeInSeconds = pigeonVar_list[4] as Double?
      val remainingDistanceInMeters = pigeonVar_list[5] as Double?
      return VehicleUpdateDto(
        vehicleState,
        location,
        destinationWaypoint,
        route,
        remainingTimeInSeconds,
        remainingDistanceInMeters,
      )
    }
  }

  fun toList(): List<Any?> {
    return listOf(
      vehicleState,
      location,
      destinationWaypoint,
      route,
      remainingTimeInSeconds,
      remainingDistanceInMeters,
    )
  }

  override fun equals(other: Any?): Boolean {
    if (other !is VehicleUpdateDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())
  }

  override fun hashCode(): Int = toList().hashCode()
}

private open class messagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let { DriverApiTypeDto.ofRaw(it.toInt()) }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let { VehicleStopStateDto.ofRaw(it.toInt()) }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let { VehicleStateDto.ofRaw(it.toInt()) }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let { DriverStatusLevelDto.ofRaw(it.toInt()) }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let { DriverStatusCodeDto.ofRaw(it.toInt()) }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { TaskInfoDto.fromList(it) }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { VehicleStopDto.fromList(it) }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { LatLngDto.fromList(it) }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { NavigationWaypointDto.fromList(it) }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { LocationDto.fromList(it) }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { DeliveryVehicleDto.fromList(it) }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let { VehicleUpdateDto.fromList(it) }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is DriverApiTypeDto -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is VehicleStopStateDto -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is VehicleStateDto -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is DriverStatusLevelDto -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is DriverStatusCodeDto -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is TaskInfoDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VehicleStopDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is LatLngDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is NavigationWaypointDto -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is LocationDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is DeliveryVehicleDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is VehicleUpdateDto -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CommonDriverApi {
  fun initialize(
    type: DriverApiTypeDto,
    providerId: String,
    vehicleId: String,
    abnormalTerminationReportingEnabled: Boolean,
  )

  fun isInitialized(type: DriverApiTypeDto): Boolean

  fun getProviderId(type: DriverApiTypeDto): String

  fun getVehicleId(type: DriverApiTypeDto): String

  fun isLocationTrackingEnabled(type: DriverApiTypeDto): Boolean

  fun setLocationTrackingEnabled(type: DriverApiTypeDto, enabled: Boolean)

  fun getLocationReportingIntervalMillis(type: DriverApiTypeDto): Long

  fun setLocationReportingIntervalMillis(type: DriverApiTypeDto, milliseconds: Long)

  fun dispose(type: DriverApiTypeDto)

  fun getDriverSdkVersion(type: DriverApiTypeDto): String

  fun setSupplementalLocation(type: DriverApiTypeDto, location: LocationDto)

  companion object {
    /** The codec used by CommonDriverApi. */
    val codec: MessageCodec<Any?> by lazy { messagesPigeonCodec() }

    /**
     * Sets up an instance of `CommonDriverApi` to handle messages through the `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
      binaryMessenger: BinaryMessenger,
      api: CommonDriverApi?,
      messageChannelSuffix: String = "",
    ) {
      val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.initialize$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val providerIdArg = args[1] as String
            val vehicleIdArg = args[2] as String
            val abnormalTerminationReportingEnabledArg = args[3] as Boolean
            val wrapped: List<Any?> =
              try {
                api.initialize(
                  typeArg,
                  providerIdArg,
                  vehicleIdArg,
                  abnormalTerminationReportingEnabledArg,
                )
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isInitialized$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val wrapped: List<Any?> =
              try {
                listOf(api.isInitialized(typeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getProviderId$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val wrapped: List<Any?> =
              try {
                listOf(api.getProviderId(typeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getVehicleId$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val wrapped: List<Any?> =
              try {
                listOf(api.getVehicleId(typeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.isLocationTrackingEnabled$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val wrapped: List<Any?> =
              try {
                listOf(api.isLocationTrackingEnabled(typeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationTrackingEnabled$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val enabledArg = args[1] as Boolean
            val wrapped: List<Any?> =
              try {
                api.setLocationTrackingEnabled(typeArg, enabledArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getLocationReportingIntervalMillis$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val wrapped: List<Any?> =
              try {
                listOf(api.getLocationReportingIntervalMillis(typeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setLocationReportingIntervalMillis$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val millisecondsArg = args[1] as Long
            val wrapped: List<Any?> =
              try {
                api.setLocationReportingIntervalMillis(typeArg, millisecondsArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.dispose$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val wrapped: List<Any?> =
              try {
                api.dispose(typeArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.getDriverSdkVersion$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val wrapped: List<Any?> =
              try {
                listOf(api.getDriverSdkVersion(typeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.CommonDriverApi.setSupplementalLocation$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as DriverApiTypeDto
            val locationArg = args[1] as LocationDto
            val wrapped: List<Any?> =
              try {
                api.setSupplementalLocation(typeArg, locationArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DeliveryDriverApi {
  fun arrivedAtStop(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun completedStop(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun enrouteToNextStop(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun getRemainingVehicleStops(callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun setVehicleStops(stops: List<VehicleStopDto>, callback: (Result<List<VehicleStopDto>>) -> Unit)

  fun getDeliveryVehicle(callback: (Result<DeliveryVehicleDto>) -> Unit)

  companion object {
    /** The codec used by DeliveryDriverApi. */
    val codec: MessageCodec<Any?> by lazy { messagesPigeonCodec() }

    /**
     * Sets up an instance of `DeliveryDriverApi` to handle messages through the `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
      binaryMessenger: BinaryMessenger,
      api: DeliveryDriverApi?,
      messageChannelSuffix: String = "",
    ) {
      val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.arrivedAtStop$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.arrivedAtStop { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.completedStop$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.completedStop { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.enrouteToNextStop$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.enrouteToNextStop { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getRemainingVehicleStops$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRemainingVehicleStops { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.setVehicleStops$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stopsArg = args[0] as List<VehicleStopDto>
            api.setVehicleStops(stopsArg) { result: Result<List<VehicleStopDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.DeliveryDriverApi.getDeliveryVehicle$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeliveryVehicle { result: Result<DeliveryVehicleDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RidesharingDriverApi {
  fun setVehicleState(state: VehicleStateDto)

  companion object {
    /** The codec used by RidesharingDriverApi. */
    val codec: MessageCodec<Any?> by lazy { messagesPigeonCodec() }

    /**
     * Sets up an instance of `RidesharingDriverApi` to handle messages through the
     * `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
      binaryMessenger: BinaryMessenger,
      api: RidesharingDriverApi?,
      messageChannelSuffix: String = "",
    ) {
      val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.google_driver_flutter.RidesharingDriverApi.setVehicleState$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = args[0] as VehicleStateDto
            val wrapped: List<Any?> =
              try {
                api.setVehicleState(stateArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AuthTokenEventApi(
  private val binaryMessenger: BinaryMessenger,
  private val messageChannelSuffix: String = "",
) {
  companion object {
    /** The codec used by AuthTokenEventApi. */
    val codec: MessageCodec<Any?> by lazy { messagesPigeonCodec() }
  }

  fun getToken(taskIdArg: String?, vehicleIdArg: String?, callback: (Result<String>) -> Unit) {
    val separatedMessageChannelSuffix =
      if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
      "dev.flutter.pigeon.google_driver_flutter.AuthTokenEventApi.getToken$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, vehicleIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(
            Result.failure(
              FlutterError(
                "null-error",
                "Flutter api returned null value for non-null return value.",
                "",
              )
            )
          )
        } else {
          val output = it[0] as String
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VehicleReporterListenerApi(
  private val binaryMessenger: BinaryMessenger,
  private val messageChannelSuffix: String = "",
) {
  companion object {
    /** The codec used by VehicleReporterListenerApi. */
    val codec: MessageCodec<Any?> by lazy { messagesPigeonCodec() }
  }

  fun onDidSucceed(vehicleUpdateArg: VehicleUpdateDto, callback: (Result<Unit>) -> Unit) {
    val separatedMessageChannelSuffix =
      if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidSucceed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(vehicleUpdateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }

  fun onDidFail(
    vehicleUpdateArg: VehicleUpdateDto,
    errorCodeArg: String,
    errorMessageArg: String,
    callback: (Result<Unit>) -> Unit,
  ) {
    val separatedMessageChannelSuffix =
      if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
      "dev.flutter.pigeon.google_driver_flutter.VehicleReporterListenerApi.onDidFail$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(vehicleUpdateArg, errorCodeArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DriverStatusListenerApi(
  private val binaryMessenger: BinaryMessenger,
  private val messageChannelSuffix: String = "",
) {
  companion object {
    /** The codec used by DriverStatusListenerApi. */
    val codec: MessageCodec<Any?> by lazy { messagesPigeonCodec() }
  }

  fun onStatusUpdate(
    levelArg: DriverStatusLevelDto,
    codeArg: DriverStatusCodeDto,
    messageArg: String,
    errorCodeArg: String?,
    errorMessageArg: String?,
    callback: (Result<Unit>) -> Unit,
  ) {
    val separatedMessageChannelSuffix =
      if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName =
      "dev.flutter.pigeon.google_driver_flutter.DriverStatusListenerApi.onStatusUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(levelArg, codeArg, messageArg, errorCodeArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
