# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run test and build
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-dart:
    name: Run dart unit tests
    timeout-minutes: 45
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          flutter-version: "3.38.x"
          channel: "stable"
          cache: true
      - name: Setup melos
        uses: bluefireteam/melos-action@3ddd2cf0f7cf2de348b114c25d953dd8fbd62907
        with:
          melos-version: "6.3.2"
      - name: "Run flutter test"
        run: melos run test:dart

  test-android:
    name: Run Android native unit tests
    timeout-minutes: 45
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          flutter-version: "3.38.x"
          channel: "stable"
          cache: true
      - name: Setup melos
        uses: bluefireteam/melos-action@3ddd2cf0f7cf2de348b114c25d953dd8fbd62907
        with:
          melos-version: "6.3.2"
      - name: "Run Android native unit tests"
        run: melos run test:android

  test-ios:
    name: Run iOS native unit tests
    timeout-minutes: 45
    runs-on:
      labels: macos-latest-xlarge
    env:
      working_directory: "example"
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          flutter-version: "3.38.x"
          channel: "stable"
          cache: true
      - name: Setup melos
        uses: bluefireteam/melos-action@3ddd2cf0f7cf2de348b114c25d953dd8fbd62907
        with:
          melos-version: "6.3.2"
      - name: Cache podfiles
        uses: actions/cache@v4
        with:
          path: "**/Pods"
          key: ${{ runner.os }}-pods-${{ hashFiles('**/*.podspec') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Select XCode 26.3
        run: sudo xcode-select -s '/Applications/Xcode_26.3.0.app/Contents/Developer'
      - name: Generate necessary files with flutter build
        working-directory: ${{ env.working_directory }}
        run: flutter build ios --config-only --simulator
      - name: "Run iOS native unit tests"
        run: TEST_DEVICE='iPhone 16 Pro' TEST_OS='26.2' melos run test:ios

  build-android:
    name: Build Android
    needs: [test-dart, test-android, test-ios]
    if: contains(github.base_ref, 'main')
    timeout-minutes: 45
    runs-on:
      labels: ubuntu-latest
    env:
      MAPS_API_KEY: ${{ secrets.ACTIONS_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          flutter-version: "3.38.x"
          channel: "stable"
          cache: true
      - name: Setup melos
        uses: bluefireteam/melos-action@3ddd2cf0f7cf2de348b114c25d953dd8fbd62907
        with:
          melos-version: "6.3.2"
      - name: "Run build for Android"
        run: melos run flutter-build-android

  build-ios:
    name: Build iOS
    needs: [test-dart, test-android, test-ios]
    if: contains(github.base_ref, 'main')
    timeout-minutes: 90
    runs-on: macos-latest-xlarge
    env:
      MAPS_API_KEY: ${{ secrets.ACTIONS_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          flutter-version: "3.38.x"
          channel: "stable"
          cache: true
          architecture: x64
      - name: Setup melos
        uses: bluefireteam/melos-action@3ddd2cf0f7cf2de348b114c25d953dd8fbd62907
        with:
          melos-version: "6.3.2"
      - name: Cache podfiles
        uses: actions/cache@v4
        with:
          path: "**/Pods"
          key: ${{ runner.os }}-pods-${{ hashFiles('**/*.podspec') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Select XCode 26.3
        run: sudo xcode-select -s '/Applications/Xcode_26.3.0.app/Contents/Developer'
      - name: "Run build for iOS"
        run: melos run flutter-build-ios
